### ISSUE TITLE
css styles conflicting with mod_quiz styles

### ISSUE THREAD

**Issue by moodleulpgc** [frankkoch/moodle-mod_studentquiz#101]
Hi:
We use the queston bank showing both question name and question text. 

Visualization of questions in the #categoryquestions table (in JS popup to add questions to a quiz) is badly affectedin mod_quiz by styles defined in mod_studentquiz because the css selectors (id, classes are the same). 

Specifically, #categoryquestions css rules defined in mod/studentquiz/styles.php also affect, conflict with, displaying  of mod_quiz add question popup. 

The several rules for #categoryquestions should be more specific, if needed, by using 
#page-mod-studentquiz-view #categoryquestions ...

**Comment by moodleulpgc** [comment]
Hi again, by the way, this is probably the same issue commented by Polaris Lee on pluigns directory on 
mié, 13 de mar de 2019, 20:19

**Comment by dionysius** [comment]
Hi @moodleulpgc 

Thanks for your report. I've fixed the styling issue by cleaning up and prefixing everything so every style stays contained within StudentQuiz. (Unfortunately there's no SCSS option in plugins).

Anyway, this fix is included in the next release. If you want it now, download https://raw.githubusercontent.com/frankkoch/moodle-mod_studentquiz/master/styles.css and replace mod/studentquiz/style.css with it. Afterwards run `php admin\cli\build_theme_css.php` from your moodle directory. (Or just wait for the next release)
