### ISSUE TITLE
Problems with comments on questions' answers

### ISSUE THREAD

**Issue by mazzar** [frankkoch/moodle-mod_studentquiz#102]
Hi there,
it seems that there is a bug when we add a comment to a question during the quiz run.

When we enter a comment, the next time we run the quiz and press the 'check' button of the question, we get this error:

```
Debug info: SELECT * FROM {context} WHERE id = ?
[array (
0 => XXXXXXXX,
)]
Error code: invalidrecord

Stack trace:
line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 4987 of /lib/accesslib.php: call to moodle_database->get_record()
line 1242 of /lib/weblib.php: call to context::instance_by_id()
line 660 of /mod/studentquiz/locallib.php: call to format_text()
line 1279 of /mod/studentquiz/renderer.php: call to mod_studentquiz_comment_renderer()
line 1405 of /mod/studentquiz/renderer.php: call to mod_studentquiz_attempt_renderer->comment_list()
line 284 of /mod/studentquiz/attempt.php: call to mod_studentquiz_attempt_renderer->render_comment()
```

We are using studentquiz v3.2.3 rel. 2019031100 on moodle V. 3.4.6+ (Build: 20181201).

**Comment by dionysius** [comment]
hi mazzar

Is XXXXXX actually the value there or have you redacted it?

In any case, could you please try to get the request information by using the developer tools (F12 in most browsers). I would be interested in the submitted values in the corresponding request the error occurs.

The following example is for the adding comments, but I'm probably only interested in the request when you press 'check'.
![2019-03-29 00_54_18-Window](https://user-images.githubusercontent.com/1341084/55200192-606dfb00-51bd-11e9-98f6-8b239468e162.png)

**Comment by mazzar** [comment]
Hi,
of course, I changed the code with XXXXX because the exact ID was not relevant. Here there is the header of the page that shows the error:

```
Summary
URL: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386958&id=55&slot=1#q1
URL: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386958&id=55&slot=1#q1
Status: 200 OK
Source: Network
Address: 195.176.55.121:443

Request
GET /mod/studentquiz/attempt.php
Referer: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386958&id=55&slot=1
Origin: https://test7.icorsi.ch
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryLJUcdfebZnrBQyEs
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15

Redirect Response
303 See Other
Location: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386958&id=55&slot=1
Pragma: no-cache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Date: Fri, 29 Mar 2019 06:57:46 GMT
Cache-Control: no-store, no-cache, must-revalidate

Request
POST /mod/studentquiz/attempt.php HTTP/1.1
Cookie: _pk_id.42.1ef6=84aaa3e7954b31f6.1551947077.12.1553842660.1553841327.; _pk_ses.42.1ef6=1; MoodleSessionelabm2=akfuhn3njro943vimjcf191abp; _shibsession_64656661756c7468747470733a2f2f74657374372e69636f7273692e63682f73686962626f6c657468=_6b890cd35c738a96afe60b2a506dc136; _pk_ref.42.1ef6=%5B%22%22%2C%22%22%2C1553841327%2C%22https%3A%2F%2Fwww.icorsi.ch%2Fmod%2Flti%2Flaunch.php%3Fid%3D404334%26triggerview%3D0%22%5D; _pk_id.14.1ef6=9a1fe39fcc38488f.1545037309.5.1549615780.1549615763.; _pk_ref.14.1ef6=%5B%22%22%2C%22%22%2C1549615763%2C%22https%3A%2F%2Flogin2.usi.ch%2Fidp%2Fprofile%2FSAML2%2FRedirect%2FSSO%3Fexecution%3De2s1%22%5D
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Origin: https://test7.icorsi.ch
Accept-Encoding: br, gzip, deflate
Host: test7.icorsi.ch
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
Accept-Language: en-us
Referer: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386958&id=55&slot=1
Connection: keep-alive

Response
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Keep-Alive: timeout=5, max=99
Pragma: no-cache
Content-Language: en
Transfer-Encoding: Identity
Expires
Cache-Control: private, pre-check=0, post-check=0, max-age=0, no-transform
Date: Fri, 29 Mar 2019 06:57:46 GMT
Connection: Keep-Alive
Accept-Ranges: none
Server: Apache/2
Content-Style-Type: text/css
X-UA-Compatible: IE=edge
Content-Script-Type: text/javascript

Query String Parameters
cmid: 386958
id: 55
slot: 1

Request Data
MIME Type
Request Data: 

```

the debugger:


```
Debug info: SELECT * FROM {context} WHERE id = ?
[array (
0 => 386958,
)]
Error code: invalidrecord
```

**Comment by dionysius** [comment]
I think I found the issue regarding comment list, please try [release 3.3.0](https://github.com/frankkoch/moodle-mod_studentquiz/releases)

**Comment by mazzar** [comment]
Hi, I don't get the error message anymore. Thanks a lot.
But, when I click the "add comment" button, the list of comments that were displayed below suddenly disappears.  If I want to see the comments (including the one I just entered), I have to start a new quiz and answer the question.
Is that the intended behaviour? 
Regards

**Comment by dionysius** [comment]
No, that should not happen. Erm, in this case I assume an error happens during loading of the AJAX comments_list.php. What is the response of that call?

**Comment by mazzar** [comment]
This is the response

Summary
URL: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386956&id=65&slot=1#q1
URL: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386956&id=65&slot=1#q1
Status: 200 OK
Source: Network
Address: 195.176.55.121:443

Request
GET /mod/studentquiz/attempt.php
Referer: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386956&id=65&slot=1
Origin: https://test7.icorsi.ch
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryclyXWPTYAtjz28HD
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15

Redirect Response
303 See Other
Location: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386956&id=65&slot=1
Pragma: no-cache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Date: Tue, 02 Apr 2019 12:41:45 GMT
Cache-Control: no-store, no-cache, must-revalidate

Request
POST /mod/studentquiz/attempt.php HTTP/1.1
Cookie: _pk_id.42.1ef6=84aaa3e7954b31f6.1551947077.14.1554208903.1554208415.; _pk_ses.42.1ef6=1; MoodleSessionelabm2=ib689tjt33u216ea7gn6nmg62j; _pk_ref.42.1ef6=%5B%22%22%2C%22%22%2C1554208415%2C%22https%3A%2F%2Fwww.icorsi.ch%2Fmod%2Flti%2Flaunch.php%3Fid%3D404334%26triggerview%3D0%22%5D; _shibsession_64656661756c7468747470733a2f2f74657374372e69636f7273692e63682f73686962626f6c657468=_9d80be0f1f58ba02da66859cf0441159; _pk_id.14.1ef6=9a1fe39fcc38488f.1545037309.5.1549615780.1549615763.; _pk_ref.14.1ef6=%5B%22%22%2C%22%22%2C1549615763%2C%22https%3A%2F%2Flogin2.usi.ch%2Fidp%2Fprofile%2FSAML2%2FRedirect%2FSSO%3Fexecution%3De2s1%22%5D
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Origin: https://test7.icorsi.ch
Accept-Encoding: br, gzip, deflate
Host: test7.icorsi.ch
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
Accept-Language: en-us
Referer: https://test7.icorsi.ch/mod/studentquiz/attempt.php?cmid=386956&id=65&slot=1
Connection: keep-alive

Response
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Keep-Alive: timeout=5, max=96
Pragma: no-cache
Content-Language: en
Transfer-Encoding: Identity
Expires
Cache-Control: private, pre-check=0, post-check=0, max-age=0, no-transform
Date: Tue, 02 Apr 2019 12:41:45 GMT
Connection: Keep-Alive
Accept-Ranges: none
Server: Apache/2
Content-Style-Type: text/css
X-UA-Compatible: IE=edge
Content-Script-Type: text/javascript

Query String Parameters
cmid: 386956
id: 65
slot: 1

Request Data
MIME Type
Request Data:

**Comment by dionysius** [comment]
I think I'm a bit lost on this one and I seem not to be on the right track. I need a reset of the investigation If you don't mind, beginning with the visual representation.

As a little background: The handling and appearance of comments in the _preview question_ window and the _question attempt within the quiz_ are identical with one exception: In the attempt the comment section (and rating) is only shown after answering the question. In both szenarios, there are two ways for showing the comments list. In the beginning, the comment list is (or should) already embedded during page load the comment list and once you add a new comment, the comment list is refreshed by requesting them in the background directly after the adding (hence AJAX request). So far so good.

First, I'd like to know the current behavior, before and after commenting (thats why I try to request these informations explicitly according to the background above). An that for both szenarios (therefore once preview question and once "real" question attempt), so I'm able to find out, if they behave the same or not (they should behave the same).

Second, what do you actually see? I assume the textfield and the button are always there, but whats below - just empty - or something along those lines: "There are no comments"? How does it change after you tried to add a comment? By the way, since that is a background request, the response is slightly delayed (but should not be longer that a few seconds - depends on how fast your moodle is in general). 

And last, do (email) notifications work in your moodle? Sending a comment to a question of a different person will attempt to send a (email) notification. The kind of notification is in your moodle globally. I don't want to investigate too much in the notifications now, but during this writeup I recognise that there is some notification code too.

**Comment by mazzar** [comment]
Hi,

the studentquiz module is currently running in a testing platform. Cron and email notification are disabled in the testing platform. Could it be the issue ?

I can provide you an access to the course, so you can try by yourself. Log on with shibboleth at our platform:

https://test7.icorsi.ch/  (Select login AAI)

then tell me your username or email address, so I can add you as student to the course.

Riccardo

**Comment by dionysius** [comment]
Sure, I'll have a look. I don't have an shibboleth account anymore, since I graduated a year ago. I send you an email, so we can work this out privately. I'll post results/findings here.

**Comment by dionysius** [comment]
The observed error was:
```
* line 488 of \/lib\/pagelib.php: coding_exception thrown
* line 1544 of \/lib\/pagelib.php: call to moodle_page->magic_get_context()
* line 677 of \/lib\/pagelib.php: call to moodle_page->initialise_theme_and_output()
* line 820 of \/lib\/pagelib.php: call to moodle_page->magic_get_theme()
* line 87 of \/filter\/emoticon\/filter.php: call to moodle_page->__get()
* line 68 of \/filter\/emoticon\/filter.php: call to filter_emoticon->replace_emoticons()
* line 176 of \/lib\/filterlib.php: call to filter_emoticon->filter()
* line 218 of \/lib\/filterlib.php: call to filter_manager->apply_filter_chain()
* line 1306 of \/lib\/weblib.php: call to filter_manager->filter_text()
* line 661 of \/mod\/studentquiz\/locallib.php: call to format_text()
* line 54 of \/mod\/studentquiz\/comment_list.php: call to mod_studentquiz_comment_renderer()
```
Somehow the $PAGE->context was not correctly set, I observed the require_login() we use there does differ from other pages, so I adapted this.

Could you try and replace your list_comments.php with [this current file](https://raw.githubusercontent.com/frankkoch/moodle-mod_studentquiz/e467e62e4c31b46f6fcec101bc88d4ec86dbd3e6/comment_list.php) - so I don't have to make a whole release because of that - and check if the issue has been fixed?
