### ISSUE TITLE
How to clean "Can not find data record in database table" ?

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#103]
Hello,

with the fresh StudentQuiz, I got "Can not find data record in database table" (https://docs.moodle.org/35/en/error/moodle/invalidrecord) upon clicking on the question preview. Somehow the rating and comments under few new questions got lost.  

Any help, please ?

**Comment by miroi** [comment]
Well, this situation happens when I, as teacher, switch my role to student, run short quiz in StudentQuiz and  add rating/comments to questions.  These questions rating/comments somehow got corrupted, giving "Can not find data record in database table".

**Comment by miroi** [comment]
Possible workaround is to make the copy and delete the corrupted question. But the question authorship gets lost.

**Comment by miroi** [comment]
Well, it seems there is some database corruption in adding rating/comments to StudentQuiz questions. After adding first rating/comment to a question the database get hurt...

**Comment by miroi** [comment]
It is also possible that this situation with StudentQuiz 3.2.3 happend because user was removed from the course and all questions created by him with rating/comments remained in the StudentQuiz.

![studentQuiz](https://user-images.githubusercontent.com/1047336/55305130-3cc1e380-544f-11e9-82b5-a9853618317a.png)

**Comment by frankkoch** [comment]
I tried to follow your decription to switch the role from teacher to student, then run a quiz with commenting questions, then go back to teacher. Unfortunately I cannot reproduce the error.

Could you please try to reproduce the scenario and give me a step-by-step description. And what Moodle version are you using?

**Comment by miroi** [comment]
Hi, 

I have Moodle 3.5.3+ (Build: 20190111), StudentQuiz 3.2.3.

In the Moodle portal, I created (as teacher) new StudentQuiz. As a student, I created new question there (multiple choice), and added rating with short comment. When I tried to preview the question, it gives the error . Also teacher can not do the question  preview due to the error.

![StudentQuizError](https://user-images.githubusercontent.com/1047336/55318156-5f192880-5472-11e9-9e1f-c1bb154cfef3.png)

**Comment by miroi** [comment]
Upon checking StudentQuiz-es throughout the Moodle portal I am administrating, I see database corruption for ratings/comments  also in other StudentQuiz instances. But I do not know clear way yet how to simulate this bug...

**Comment by dionysius** [comment]
I think I found the issue regarding comment list, please try [release 3.3.0](https://github.com/frankkoch/moodle-mod_studentquiz/releases)

**Comment by dionysius** [comment]
Reopening, as I think there is a thing more going on. But so far I'm not able to reproduce the coruption issue.

**Comment by miroi** [comment]
It works again ! Added ratings and comments in my updated StudentQuiz instances are showing up again.

Right, this was only "visual" bug, because after adding rating/comments they showed up in the question list, but did not show up through the preview.

Closing this issue as solved. Thanks !
