### ISSUE TITLE
Can not display all filtered questions

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#105]
Hello,

with the fresh StudentQuiz (and Moodle 3.5) I can not display all filtered questions if they number exceed default number of questions per page.  When I click on display all question after filtering, it shows all questions in StudentQuiz, not those filtered out.

Increasing the number of questions per page does not help - after filtering it returns to the (lower) default value of 20.

Any help, please ?

**Comment by dionysius** [comment]
Fixed with #112, next release coming soon containing the fix.

**Comment by miroi** [comment]
ok, thanks, looking forward for the fresh release.
