### ISSUE TITLE
restoring StudentQuiz from the course backup

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#109]
Hello,
we suffered sudden disappearing of all the questions in 2 StudentQuiz instances in Moodle 3.5. 
When I was trying to restore StudentQuiz from the backup file, it failed on [https://docs.moodle.org/35/en/error/moodle/dmlwriteexception](https://docs.moodle.org/35/en/error/moodle/dmlwriteexception) . 

Any help, please ?

**Comment by miroi** [comment]
Hi,
as workaround I manually imported saved xml files with questions into the empty StudentQuiz question category. What was lost was author's  assignement, rating and comments. Authors names are written in questions  general feedback part, but one can not search the text there - see https://github.com/frankkoch/moodle-mod_studentquiz/issues/110 .

Also, would it be difficult to have feature allowing assignement of a new author (owner) to selected questions ?

**Comment by dionysius** [comment]
Hi @miroi , I've seen your comment in the other issue about this issue still failing for you. We already have [a test](https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/tests/behat/moodle_backup.feature) for restoring course backups in which the questions still exist. We have a hard time to even closely reproduce your issue. I'm kinda urged to ask you for a course backup which is affected from this issue, but I'm concerned for privacy issues for your organisation and your users if you provide me such. What options do you have? My plan would be inspecting your backup file and restoring your backup in one of my development moodles and have a close look into the result.

**Comment by miroi** [comment]
Hi @dionysius , thanks for your interest. I will return to this issue after getting the most recent upgrade. To bypass privacy issue I would pack only the studentquiz and some quizess into the backup file, without any data about users, their activities etc.

**Comment by dionysius** [comment]
This has been unresponded since a while. I'm happy to analyze a moodle backup if one comes up - don't forget to anonymize before sending
