### ISSUE TITLE
searching through the general feedback

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#110]
Hello,
current searching covers the question's text body. Would it be please possibe to have also the searching through the question's general feedback text  ? Thanks.

**Comment by miroi** [comment]
The main reason is that the general feedback section may contain important text to be searched for   - like the author names. This is our case.

**Comment by dionysius** [comment]
It's been a while and we were discussing it internally quite a while. We currently can't see such feature coming anytime soon.
