### ISSUE TITLE
author assignment to questions ? 

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#114]
Hello, 
would it be please difficult to have new feature allowing assignment of a new author (owner) to selected questions ?

This is because upon exporting/importing (restoring) questions from/to StudentQuiz the teacher who did the import becomes the new owner (author) of all questions. 

It would be good to change questions authorship to students so they as owners will be able to edit their new and selected (semi-finished) questions.

**Comment by frankkoch** [comment]
The purpose of the export file is to transfer questions from one course to another. The group of students at the destination course might be different from the origin course.

If you don't want to become the owner of the questions, I suggest you to create a dummy user for the import.

If you need the original question owners, don't work with export/import, but create a course backup and make a restore.

**Comment by miroi** [comment]
Thanks for your response, Frank. I just need this functionality for restoring lost questions authorship from StudentQuiz, see https://github.com/frankkoch/moodle-mod_studentquiz/issues/109 .
