### ISSUE TITLE
Datensatz kann nicht in der Datenbanktabelle context gefunden werden.

### ISSUE THREAD

**Issue by sehomer** [frankkoch/moodle-mod_studentquiz#121]
Guten Tag,

bei mehreren Fragen kommt es zu folgender Meldung bei der Preview oder beim Starten des Student Quiz: Datensatz kann nicht in der Datenbanktabelle context gefunden werden.

`Debug info: SELECT * FROM {context} WHERE id = ?
[array (
0 => 528132,
)]
Error code: invalidrecord
×
Stack trace:
* line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 5023 of /lib/accesslib.php: call to moodle_database->get_record()
* line 1242 of /lib/weblib.php: call to context::instance_by_id()
* line 660 of /mod/studentquiz/locallib.php: call to format_text()
* line 1279 of /mod/studentquiz/renderer.php: call to mod_studentquiz_comment_renderer()
* line 1405 of /mod/studentquiz/renderer.php: call to mod_studentquiz_attempt_renderer->comment_list()
* line 1303 of /mod/studentquiz/renderer.php: call to mod_studentquiz_attempt_renderer->render_comment()
* line 144 of /mod/studentquiz/preview.php: call to mod_studentquiz_attempt_renderer->feedback()
`

**Comment by sehomer** [comment]
Momentan ist noch Version 3.2.3 in Moodle 3.4 installiert.

**Comment by dionysius** [comment]
Hi @sehomer 

You'll probably have run into a [bug, which has already been fixed](https://github.com/frankkoch/moodle-mod_studentquiz/commit/d5e221db36a3f2bdb9ca9dc2c3dcbd720f3a883a) for v3.3.0 and onwards.
