### ISSUE TITLE
Navigation to return to bank is missing after completing a quiz

### ISSUE THREAD

**Issue by reactor0138** [frankkoch/moodle-mod_studentquiz#14]
If you do a quiz and then want to go bank and start a new quiz with different filters you need to go bank to the front of the course and click on the student quiz.

Ideally there would be navigation back to the bank once you have finished a quiz

**Comment by frankkoch** [comment]
Yes, but we did not find a suitable way to improve this, and since it is just one more click it was dropped from the Todo-list. Sorry

**Comment by reactor0138** [comment]
Thanks Frank For addressing all the issues. We have found it is our server giving us the slow load time (our other test and live versions are fine). In the activity there is no description like other activities so no way to leave a description on how to use the tool. We will make a video and put it outside. But that might be a good improvement. With the show filters things we thought it might be a good option in settings. then users can choose to show or hide. Thanks again for all your responses, Much appreciated Cheers Scott

**Comment by reactor0138** [comment]
Nick and I hope to look into this again as on a big course this is causing a lot of hassles for student to navigate out then search a big course (having to remember one of numerous practice quizzes) find the quiz and click on it.
