### ISSUE TITLE
Fix behat tests

### ISSUE THREAD

**Issue by ewallah** [frankkoch/moodle-mod_studentquiz#150]
The comment in the travis file "with Firefox, which mostly works, but has a spurious fail at the end, so ingore (dixit) results for now." is a bit misleading. Nowadays behat is failing 6 times in firefox and chrome.

**Comment by dionysius** [comment]
Behat tests are back enabled, I've fixed the tests which were flaky. There's still a test failing in master, but that's currently correctly failing.

**Comment by ewallah** [comment]
Thanks a million!
