### ISSUE TITLE
Documentation link is a deadlink

### ISSUE THREAD

**Issue by lucaboesch** [frankkoch/moodle-mod_studentquiz#155]
This

<img width="492" alt="grafik" src="https://user-images.githubusercontent.com/377279/63420723-9b402c00-c407-11e9-8a16-7d1f5e0def01.png">

Link to
https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/manuals/User-Manual.pdf
is not working.

**Comment by dionysius** [comment]
Someone familiar with [AMOS](https://lang.moodle.org/local/amos/)? The [provided english translation](https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/lang/en/studentquiz.php#L189) is already gone thanks to OP's PR in the past.

**Comment by lucaboesch** [comment]
I already edited the string out in AMOS for de and es.
IMHO you can leave the rest of the work to the AMOS contributors in the different languages.
This is no more of your concern: therefore I propose to close this one.
