### ISSUE TITLE
Quiz filters not obvious and are hidden

### ISSUE THREAD

**Issue by reactor0138** [frankkoch/moodle-mod_studentquiz#16]
When on the quiz creation page it is not obvious that there are filters and perhaps it would be better if the filters were all open instead of being hidden in a dropdown behind the word filter. Maybe like the student filter when browsing users we could have the first 2-3 filters open and then show more. This would be more obvious for students

**Comment by frankkoch** [comment]
Thank you. We discussed this issue and we decided to show a collapsed filter only such that we have more space available for the precious questions.
