### ISSUE TITLE
I can't upgrade sudentquiz, because I downgrade it before.

### ISSUE THREAD

**Issue by tangsonglin** [frankkoch/moodle-mod_studentquiz#161]
Several days ago , I upgrade moodle 3.7.1+(build:20190824). I reported that Studentquiz(v4.03) can't work within moodle. 
I modify the studentquiz vision from my carelessness.  In database, I UPDATE mdl_config_plugins SET value = '2019072300' WHERE mdl_config_plugins.plugin=mod_studentquiz; And I reinstalled studentquiz v4.01(2019072300). It worked well.
Last night , I 'm happy to hear new vision 4.04 . I want to upgrad it .
But I can't.  Moodle tells me , 
"Plugin "mod_rf" is defective or outdated, can not continue, sorry.
×Debug info: Missing version.php
Error code: detectedbrokenplugin"
See the attachment for details，please.
![upgrade_moodle_error_01](https://user-images.githubusercontent.com/37798622/63995585-ac85e880-cb2b-11e9-86c1-891cf8f6708b.PNG)
[error_text01.txt](https://github.com/frankkoch/moodle-mod_studentquiz/files/3558416/error_text01.txt)

**Comment by tangsonglin** [comment]
Each time Moodle is managed, an upgrade prompt appears and the same error is repeated.
In spite of this, other users can still use the website normally, and the studentquiz plug-in.
But I can't manager moodle and users, and others.
Can you tell me what to do?

**Comment by lucaboesch** [comment]
Tang, that has nothing to do with StudentQuiz.
The error message leads me to think you accidantially made a 'rf' folder under /mod (probably by a incorrect shell command).
Can you please check on this.

**Comment by tangsonglin** [comment]
> Tang, that has nothing to do with StudentQuiz.
> The error message leads me to think you accidentially created a 'rf' folder (probably empty) under /mod (probably by a incorrect shell command).
> Can you please check on this.

I saw this folder. After I deleted it, moodle successfully upgraded the plugin. Thank you very much. I am really careless. I worked hard for one night, but your great words helped me solve the problem. Thank you. Best to you !
