### ISSUE TITLE
error/moodle/missingparam

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#165]
Hello, with Moodle 3.7 and the fresh StudentQuiz I am getting the error error/moodle/missingparam when I am moving selected questions in StudentQuiz to a subdirectory under StudentQuiz module.

This is the way I am used  to export selected questions from StudentQuiz: I select some questions and move them into StudentQuiz subcategory, from where I export them.

As I checked, after showing this error selected questions are moved under the subcategory.

Any help, please ?

**Comment by dionysius** [comment]
I've noticed that as well. Currently moving questions to subcategories is broken.

**Comment by HuongNV13** [comment]
Just spot this at OU

I'm working on it.

Patch will be provide soon

Thanks,

**Comment by miroi** [comment]
Hello,

maybe this is related to this bug, but I got lost of more than 500 questions from StudentQuiz without any deletion. (This is second time).

 Upon recovery I imported them (in xml format) from restored Moodle. But when changing status to visible I got error https://docs.moodle.org/37/en/error/moodle/missingparam . 

I would welcome fix of this issue as well as fix of https://github.com/frankkoch/moodle-mod_studentquiz/issues/109 .

**Comment by miroi** [comment]
Well, again, with the fresh StudentQuiz 4.0.5 and  Moodle 3.7 I am getting the same error https://docs.moodle.org/37/en/error/moodle/missingparam when moving tag-selected questions to existing StudentQuiz subcategory before exporting them.

Although this bug shows up, selected questions are moved into desired StzudentQuiz subcategory.

**Comment by dionysius** [comment]
Unfortunately the `missingparam` error could happen everywhere. Could you please [enable debugging in "DEVELOPER" mode](https://docs.moodle.org/37/en/Debugging) for a short time and report the additional informations.
