### ISSUE TITLE
Approved question in StudentQuiz

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#166]
Hello,
when a question is approved by teacher, question´s author can not edit his question. However, he is allowed to delete it.

Would you please agree with removing the right for deleting of the approved question by the student-author  ? I think when a question is approved, not only editing by author is prohibited, let the deleting be prohibited as well.

**Comment by frankkoch** [comment]
Hi Miroi, I hesitate to do this. The question is *owned* by the author and she should not be stopped to delete her work. A student could even legally enforce the deletion by using her rights ensured by the GDPR.

**Comment by miroi** [comment]
OK, thanks for your statement.
