### ISSUE TITLE
Import of questions into the student quiz from other banks

### ISSUE THREAD

**Issue by reactor0138** [frankkoch/moodle-mod_studentquiz#17]
This may be a bug but could just be me. It appears to have the same issue as question built in a quiz or in the question creation tool. I can't find a way to move questions into the bank for the student quiz. It looks like its totally hidden.  I can't even export them and then import them. This is not very efficient. I'm sure the tool creates its own bank somewhere but you can't even get to it. There is no way to move questions into a category/bank you cannot see. Only move questions from the tool to another bank. If you have a whole lot of questions and want to make categories too then you can't.

**Comment by frankkoch** [comment]
Thank you. We discussed this issue and we decided to show a collapsed filter only such that we have more space available for the precious questions.

**Comment by frankkoch** [comment]
Questions created with a StudentQuiz ABC will be stored in the questionbank category "Standard for ABC". Within SQ, they can be moved into other categories. You could also export questions into different data formats for external use. Or you can import e.g. GIFT or XML based questions into "Standard for ABC".

**Comment by reactor0138** [comment]
Hi Frank
The import as you suggest does not appear to work. Using xml or gift and even if you take the name of the category of the student quiz it does not import into that category.
xt>$module$/Default for Ortho MCQ Creation &amp; Filtered Quizzes</text> gives you an import into the category you are in and since you can't get to an import page for the student quiz it does not work. 
xt>$course$/Default for Ortho MCQ Creation &amp; Filtered Quizzes</text>just creates another category in the main question bank with the same name as the hidden one of the student quiz. 
Please can you explain how I need to change the import file to get it into the student quiz category. I can see how it would work in theory, just match the category with the category on the student quiz, but in practice this does not work.
Hope you can help Scott

**Comment by frankkoch** [comment]
Hello Scott
I might miss your point.. Once you create a SQ-activity (lets call it "ABC") a new category "Default for ABC" becomes created. You can see this category in the SQ menue "Question bank". Next, within the SQ-activity you use the menue "Import", specify the format, and upload the question file. That's it, the questions will now show up in the category "Default for ABC".
Cheers, Frank

**Comment by reactor0138** [comment]
But that's the thing, there is no import, export option. Unlike a quiz that has the question bank option and import export. What theme are u on? Boost? Will check in morning but 4 of us can't find the usual import area. Can I send you some screen shots. scott.hallman@otago.ac.nz
