### ISSUE TITLE
StudentQuiz can't be opened after import, because the question state is missing and thus invalid

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#172]
While working on fixes I encountered this bug. Every backup, which don't contain the question state (which is since introduction of the question states in v4.0.0) can be imported without visible error, but opening the main page results in an error. Currently, all questions must have a valid state.

This issue is **not** related to any current issue reported.

The problem is, moodle seems to ignore the restore path, so I'm unable to ensure an entry exists and to set useful defaults. I've opened a bug report on the Moodle tracker: https://tracker.moodle.org/browse/MDL-67406

**Comment by dionysius** [comment]
Meanwhile, currently on master, I've improved the error message to:
```
Invalid question state `` for question `6`
```

**Comment by Marx1st** [comment]
> While working on fixes I encountered this bug. Every backup, which don't contain the question state (which is since introduction of the question states in v4.0.0) can be imported without visible error, but opening the main page results in an error. Currently, all questions must have a valid state.
> 
> This issue is **not** related to any current issue reported.
> 
> The problem is, moodle seems to ignore the restore path, so I'm unable to ensure an entry exists and to set useful defaults. I've opened a bug report on the Moodle tracker: https://tracker.moodle.org/browse/MDL-67406

Hi! Is the error "Invalid course module ID"?

**Comment by dionysius** [comment]
No, I missed the part in the description. The resulting issue here is that all questions are getting hidden in an import (moodle <=36), so not restoring the same question state it was before. The issue in the code is also tied with normal question creation and import from xml, so the fix may take a bit and I'm in talk for clarifying the expected behavior when question state informations are missing with frank and huong who initially contributed that feature. I think I have all clarifications now, but haven't made a strategy to apply the fix yet. But, I should be able to work on that soon.
