### ISSUE TITLE
Docs link in add activity dialog leads to wrong page (?)

### ISSUE THREAD

**Issue by danowar2k** [frankkoch/moodle-mod_studentquiz#174]
Hi, I don't know if this is done intentionally, but the Moodle Docs link when adding a StudentQuiz leads to a page that says it's a redirect (which it doesn't do automatically).

Shouldn't there be a direct link to the real docs? Or is this a Moodle Docs convention?

**Comment by frankkoch** [comment]
The StudentQuiz documentation is available in multiple languages. So depending on your language preference you become redirected to one place or the other.

**Comment by danowar2k** [comment]
Yeah, but the link points to http://docs.moodle.org/35/de/mod/studentquiz/view.
Shouldn't it point to https://docs.moodle.org/35/de/StudentQuiz ? Or ist this because no 3.5 docs exist?

**Comment by miroi** [comment]
Ah, concerning the documentation - I would keep only English, https://docs.moodle.org/35/en/StudentQuiz_module , and with localizations URL from there.

**Comment by lucaboesch** [comment]
> Yeah, but the link points to http://docs.moodle.org/35/de/mod/studentquiz/view.
> Shouldn't it point to https://docs.moodle.org/35/de/StudentQuiz ? Or ist this because no 3.5 docs exist?

Those redirections are done in MoodleDocs. All activities do link to http://docs.moodle.org/{wildcard for version}/{wildcard for language}/mod/{wildcard for activity name}/view

That is how the mechanism works. The code in studentquiz is correct.

Best,
Luca

**Comment by danowar2k** [comment]
Oh thanks, didn't know about that mechanism yet.
