### ISSUE TITLE
translation issue with qtype_multichoice

### ISSUE THREAD

**Issue by chscheuermann** [frankkoch/moodle-mod_studentquiz#176]
Hi,

we actually use Moodle 3.5.9+ with mod_studentquiz v4.0.4 2019082900.

In multiple choice questions (qtype_multichoice) I get german answer texts although the system language is set to english. With other question types it works well.
![qtype_multichoice](https://user-images.githubusercontent.com/59016096/71084526-c3615100-2195-11ea-865a-3ff6885b702e.jpg)

Is this issue comprehensible?

Regards,
Christian

**Comment by dionysius** [comment]
That's interesting. We use the moodle lib directly as currently in https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/attempt.php#L220 to show the whole question without any modification, the only thing I can look into is if $options needs additional specifics.

**Comment by dionysius** [comment]
![image](https://user-images.githubusercontent.com/1341084/71785333-a4b8e200-2ffe-11ea-8b83-64069ef6e08d.png)
So, on my local moodle 35 installation in english everything stays english. I've found the options here https://github.com/moodle/moodle/blob/MOODLE_35_STABLE/question/engine/lib.php#L476, but none of them are related to the language and we don't use a behaviour.

Do you have german in your moodle installed to offer that language to your students? (In my case only the default english is installed, nothing extra)

**Comment by chscheuermann** [comment]
Hi and thanks for your answer,

yes we use german as main language. I've been searching for that text in the translations but haven't found it. Don't know what's wrong :(.

Regards

**Comment by dionysius** [comment]
If my assumption is right the same should happen in a Moodle Quiz. You could setup a small Quiz activity, with such a question in it and if that user answers that question wrong the behaviour should be the same. Can you check that?

**Comment by chscheuermann** [comment]
Hmm, yes ... same here :(
![grafik](https://user-images.githubusercontent.com/59016096/72447363-8187f280-37b5-11ea-9d9a-85dcdd1339a3.png)
![grafik](https://user-images.githubusercontent.com/59016096/72447372-83ea4c80-37b5-11ea-8551-13112e2b37ab.png)

**Comment by dionysius** [comment]
Well, that confirms that I can't fix that for you, as this is a bug in Moodle then. Thanks for checking!
