### ISSUE TITLE
Submit hardcoded

### ISSUE THREAD

**Issue by dinism** [frankkoch/moodle-mod_studentquiz#192]
I'm PT-PT translator
When previewing a question, the button Submit for change the status of question is hardcoded. Can't be translated.
![imagem](https://user-images.githubusercontent.com/14828021/73497657-38d65900-43b3-11ea-9082-dfae3f194caf.png)

**Comment by dionysius** [comment]
![image](https://user-images.githubusercontent.com/1341084/74943866-61bb9e00-53f5-11ea-9041-d675a7c1d970.png)
Upcoming commit fixes it to: Using translation for "state" as the title and translation for "change state" as the button text
