### ISSUE TITLE
2 behat scenarios should have the @_switch_window tag

### ISSUE THREAD

**Issue by ewallah** [frankkoch/moodle-mod_studentquiz#199]
2 scenarios (Test filter - Test Studentquiz cannot edit approved/disapproved question) in state_visibility.feature use the "And I switch to " feature.

Some browsers have problems with handling windows. Adding the @_switch_window tag to these scenarios will inform these browsers they should skip these tests.

**Comment by ewallah** [comment]
THX a million!

R

**Comment by dionysius** [comment]
you are welcome! Since I just made a release a few days ago, this might stay in master for a little while until enough fixes have accumulated.
