### ISSUE TITLE
Marking more answers than just the correct once are revarded with full points

### ISSUE THREAD

**Issue by innerjoin** [frankkoch/moodle-mod_studentquiz#20]
If I tick all the correct answers plus one or more incorrect answers, I am revarded with full points, which is incorrect.

![studentquiz](https://user-images.githubusercontent.com/2387965/29263618-e346759a-80d9-11e7-8215-6f1dd83dcbbd.PNG)

**Comment by frankkoch** [comment]
This is not a StudentQuiz problem but due to the poor setup of this particular question. The author of the question did not configure a penalty in case of wrong answers.
![screenshot](https://user-images.githubusercontent.com/12372991/29265751-7bb92338-80e2-11e7-8911-aecad0ecaa45.JPG)
