### ISSUE TITLE
Travis behat is broken again

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#202]
https://github.com/frankkoch/moodle-mod_studentquiz/commit/de71075c48e7fae6391f095f339e4ee6df469712

**Comment by kabalin** [comment]
See https://github.com/blackboard-open-source/moodle-plugin-ci/issues/110 for workaround ;)

**Comment by dionysius** [comment]
@kabalin Thank you!

**Comment by dionysius** [comment]
Hi @kabalin 

So far I couldn't get the behat to run through completely, do you see if I missed something?
- chrome runs everything except file uploads it seems: [build & config](https://travis-ci.org/frankkoch/moodle-mod_studentquiz/builds/657717543/config)
- firefox looks like does not run anything `@javascript` marked things: [build & config](https://travis-ci.org/frankkoch/moodle-mod_studentquiz/builds/657315659/config)

**Comment by kabalin** [comment]
Hello @dionysius, upload has been fixed, take a look at my last comment at the issue: https://github.com/blackboard-open-source/moodle-plugin-ci/issues/110#issuecomment-597576207

Re firefox, not sure to be honest, try selenium version 2.53.1.
