### ISSUE TITLE
implement @_switch_window tag

### ISSUE THREAD

**Issue by ewallah** [frankkoch/moodle-mod_studentquiz#212]
3 feature files use the line **And I switch to "x" window**

- state_visibility.feature
- preview_question.feature
- comment_area_create.feature

The scenarios that use this line should implement the @_switch_window tag,

**Comment by dionysius** [comment]
Hmm... they all already have where relevant...

> state_visibility.feature

https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/tests/behat/state_visibility.feature#L60

> preview_question.feature

https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/tests/behat/preview_question.feature#L31

> comment_area_create.feature

https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/tests/behat/comment_area_create.feature#L36

**Comment by dionysius** [comment]
Relevant (20th Feb): https://github.com/frankkoch/moodle-mod_studentquiz/commit/ce18b08b24548dbb39e34607b9bdf9a19df5774c
