### ISSUE TITLE
Reopen: UI, Modal state change not working

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#218]
Followup from #184 @lamtranb @HuongNV13 

I still see flaky results with the modal javascript, sometimes it works, sometimes not. I opened this issue so it doesn't get forgotten.

Copy from there:

> I've found the reason, why the change event never gets triggered. By looking into the jquery event list for that element, we can see, that sometimes the change function is assigned (and then works), and mostly not (and obviously doesn't work).
> 
> I assume we have here some javascript timing/loading issues.
> 
> ![Screenshot from 2020-01-14 19 07 48](https://user-images.githubusercontent.com/1341084/72370034-a3c03880-3701-11ea-8e97-a9d5015cec29.png)
> vs
> ![Screenshot from 2020-01-14 19 07 13](https://user-images.githubusercontent.com/1341084/72370036-a458cf00-3701-11ea-8acd-6d2a37b722d7.png)

**Comment by HuongNV13** [comment]
I will check this next week when I start to implement the new enhancement for StudentQuiz: Edited comment history.

**Comment by dionysius** [comment]
should be fixed by #262

**Comment by dionysius** [comment]
Solution provided by #262 seems not to be sufficient, I'm still getting the disabled button pretty often on master.
