### ISSUE TITLE
StudentQuiz places its Quizes after the maximum number of sections

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#22]
Is there any help with this issue, https://moodle.org/mod/forum/discuss.php?d=358559 ?

While working with StudenQuiz, my Moodle course got the maximum number of sections... do I have to manually delete all of them ?

**Comment by frankkoch** [comment]
StudentQuiz uses the orphaned section 999 but Moodle 3.3 abolished orphaned sections. This causes the long section list. We're working on this and we're planning to release a solution by end of October.

**Comment by dionysius** [comment]
Hi @miroi

About a week ago we released a new update for studentquiz fixing your issue. You can find all informations in the release notes: https://github.com/frankkoch/moodle-mod_studentquiz/releases/latest

**Comment by miroi** [comment]
Thanks; would you please also update StudentQuiz on the side of plugins, https://moodle.org/plugins/qbehaviour_studentquiz ?

**Comment by dionysius** [comment]
Hi @miroi

It is, the question behavour hasn't changed, it's the activity plugin: https://moodle.org/plugins/pluginversions.php?plugin=mod_studentquiz
