### ISSUE TITLE
Enable privacy test for progress

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#220]
While cleaning up some code I found this commented code which should be enabled: https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/tests/privacy_test.php#L197

@HuongNV13 I think you're the privacy provider guru here, can you have a look?

**Comment by dionysius** [comment]
All lines effected marked with "Skipped for now"

**Comment by timhunt** [comment]
Just to note that there is a public holiday in Vietnam today and tomorrow (Thurs & Fri) so Huong's next working day is Monday.

**Comment by dionysius** [comment]
Noted, I probably could uncomment these and see where I land, just wanted to place this as an issue so it doesn't get forgotten

**Comment by dionysius** [comment]
#229
