### ISSUE TITLE
Students do not see their created questions

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#224]
Hello !

With Moodle 3.7 and up-to-date StudentQuiz, students, who created questions, do not see them. Teacher has to make the new questions visible manually. 

Any help, please ?

**Comment by miroi** [comment]
Well, most probably this is due to the change of students identities during the existence of StudentQuiz. The workaround is to manually open newly created questions for the visibility.

**Comment by dionysius** [comment]
This is probably related to your setting of your studentquiz:

![image](https://user-images.githubusercontent.com/1341084/81807348-304afe00-951e-11ea-8a57-ce8dc68d4ab2.png)

publishing = visible for students. Some organisation like to approve questions first before others to access it (approving a question automatically makes them visible).

What baffles me right now, that we don't allow to change it afterwards... Do you know the reason @HuongNV13 ?

**Comment by miroi** [comment]
Ad: "What baffles me right now, that we don't allow to change it afterwards... Do you know the reason" 

... indeed. I would be very glad to change this setting during the "lifetime" of StudentQuiz.

**Comment by frankkoch** [comment]
Hmm, good point. I do not see a reason to block a change once a question is added.

**Comment by HuongNV13** [comment]
According to this PR: #180 

This feature was requested by Chris Nelson (after discussing with Frank).
Because once questions are published in StudentQuiz, changing the publishing setting seems to have no effect.

**Comment by frankkoch** [comment]
Thank you Huong, this makes sense. Once questions are published you cannot toggle this option anymore, because already published questions cannot be "unpublished".

**Comment by miroi** [comment]
Fine, thanks for the clarificaton, friends. If nobody objects for some time, please close this issue.

**Comment by dionysius** [comment]
#228
