### ISSUE TITLE
Just the English strings should ship with the plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [frankkoch/moodle-mod_studentquiz#23]
Hi,

I like your plugin very much.
I made the Mexican Spanish translation for it in AMOS :)

According to https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings , "Just the English strings should ship with the plugin. All other translations are supposed to be submitted as contributions at https://lang.moodle.org once your plugin is approved - see https://docs.moodle.org/dev/Translating_plugins."

I have checked in AMOS and both the French and German translations are there.

So, you can now  safely remove the French and German translations from the plugin downloadable ZIP file.

Thanks for a very useful Moodle plugin.

**Comment by frankkoch** [comment]
Dear German

Thank you very much for your friendly response and the translation work. In fact, I've had the translation into Spanish on my todo-list for a long time, and now it comes all of the sudden. It's great to work inside such an active community. We'll make the changes in the code.

Muchisimas gracias a los amigos en Mexico!
Frank

**Comment by frankkoch** [comment]
Thank you again German for completing the Mexican translations for StudentQuiz 3.0.0. I hope you like the new release.

**Comment by germanvaleroelizondo** [comment]
My pleasure.
