### ISSUE TITLE
Code missing

### ISSUE THREAD

**Issue by HuongNV13** [frankkoch/moodle-mod_studentquiz#232]
Hi @dionysius,
I have a PR that was merged (by you) last month #211 
But for some reason, it was accidental deleted in your repo. Could you please check it?

Thanks,

**Comment by dionysius** [comment]
Hi @HuongNV13, no it was not accidental. I decided that it was unneeded since every form field helptext doesn't have a default text as well. Why should we make one for this field and not the others, since the default is always prefilled?

**Comment by timhunt** [comment]
That makes sense to me. No need to say the default in the help text. I think this can be closed.

**Comment by HuongNV13** [comment]
Thanks @dionysius for your explaination.
That makes sense.

I going to close this issue.
