### ISSUE TITLE
Error in upgrade script: Unknown column 'edituserid' in 'mdl_studentquiz_comment'

### ISSUE THREAD

**Issue by AdrianoRuseler** [frankkoch/moodle-mod_studentquiz#233]
System info:
PHP 7.2.24-0ubuntu0.18.04.4
10.3.23-MariaDB-1:10.3.23+maria~xenial - mariadb.org binary distribution 
Moodle 3.8.3+
mod_studentquiz branch: master

Error in upgrade script:

`-->mod_studentquiz
Default exception handler: Erro de execução DDL SQL Debug: Unknown column 'edituserid' in 'mdl_studentquiz_comment'
ALTER TABLE mdl_studentquiz_comment ADD status SMALLINT(4) NOT NULL DEFAULT 0 AFTER edituserid
Error code: ddlexecuteerror
* line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
* line 1072 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 77 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
* line 547 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
* line 712 of /mod/studentquiz/db/upgrade.php: call to database_manager->add_field()
* line 826 of /lib/upgradelib.php: call to xmldb_studentquiz_upgrade()
* line 532 of /lib/upgradelib.php: call to upgrade_plugins_modules()
* line 1877 of /lib/upgradelib.php: call to upgrade_plugins()
* line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! Erro de execução DDL SQL !!!
!! Unknown column 'edituserid' in 'mdl_studentquiz_comment'
ALTER TABLE mdl_studentquiz_comment ADD status SMALLINT(4) NOT NULL DEFAULT 0 AFTER edituserid
Error code: ddlexecuteerror !!
!! Stack trace: * line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
* line 1072 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database-&gt;query_end()
* line 77 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database-&gt;change_database_structure()
* line 547 of /lib/ddl/database_manager.php: call to database_manager-&gt;execute_sql_arr()
* line 712 of /mod/studentquiz/db/upgrade.php: call to database_manager-&gt;add_field()
* line 826 of /lib/upgradelib.php: call to xmldb_studentquiz_upgrade()
* line 532 of /lib/upgradelib.php: call to upgrade_plugins_modules()
* line 1877 of /lib/upgradelib.php: call to upgrade_plugins()
* line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!
Error in upgrade script...
`

**Comment by dionysius** [comment]
Thank you for the report. upgrade and restore need to be checked manually, so master is currectly unstable. Working on it

**Comment by dionysius** [comment]
Hmm... How did you get to this state? I checked the code and I can't see something wrong. If you were coming from v4.2.0, which is commit https://github.com/frankkoch/moodle-mod_studentquiz/commit/2389895daec15b7573e1a0246cca605f7d272b59, you can safely upgrade to master, which is currently commit https://github.com/frankkoch/moodle-mod_studentquiz/commit/4edaeb6e14eedcba900dff17bee09ef77c1dad30.

The field 'edituserid' was introduced for v4.2.0, in commit https://github.com/frankkoch/moodle-mod_studentquiz/commit/3d45959d6300d096ee764d437ce0991ca9c2e41f#diff-ed6e4e003c5e4a8135ff038008634782, which now gets removed https://github.com/frankkoch/moodle-mod_studentquiz/blob/4edaeb6e14eedcba900dff17bee09ef77c1dad30/db/upgrade.php#L811, but only **after** adding the status field https://github.com/frankkoch/moodle-mod_studentquiz/blob/4edaeb6e14eedcba900dff17bee09ef77c1dad30/db/upgrade.php#L712 (which your error shows - line 712)

So I don't exactly know how you got into this situation. Which version/commit were you before?

**Comment by AdrianoRuseler** [comment]
Previous version: v4.2.0 (2020050100)

As I just installed this plugin and didn't use it, all tables are empty. Could this be causing the error? Clean install runs just fine!

![image](https://user-images.githubusercontent.com/2466178/82671248-eb595280-9c14-11ea-9b9b-98469656fe73.png)

**Comment by dionysius** [comment]
Empty dataset shouldn't matter here. It was complaining about the layout of the database, which should've been fine anyway.

**Comment by dinism** [comment]
I have the same issue:
![imagem](https://user-images.githubusercontent.com/14828021/82734177-fdb8b680-9d10-11ea-8429-5c81e421c715.png)

**Comment by AdrianoRuseler** [comment]
Can the issue be related with the language package (pt_br)?

**Comment by dewray** [comment]
Same issue. 
Mariadb 5.5.5-10.1.44; php 7.2.24.0.0.18.04.4
language pack (pt_br) not in use

I have never used the plugin before (and was planning to use it next week).
![Image 103](https://user-images.githubusercontent.com/35580043/82740403-6e98b680-9d83-11ea-9855-5280e346463b.jpg)

**Comment by dionysius** [comment]
Ok, this issue happens to too many people. I need your input to find the cause. Can you paste here (before the upgrade):

- the file: `mod/studentquiz/version.php`
- the file: `mod/studentquiz/db/install.xml`
- in the DB: `show create table mdl_studentquiz`
- and: `show create table mdl_studentquiz_comments`
( the prefix `mdl_` might be different in your case )

**Comment by miroi** [comment]
Hi,

reporting the same issue, happening upon standard upgrade. So I can not do the upgrade of StudentQuiz for now.

~~~
mod_studentquiz
DDL sql execution error

More information about this error

×Debug info: Unknown column 'edituserid' in 'mdl_studentquiz_comment'
ALTER TABLE mdl_studentquiz_comment ADD status SMALLINT(4) NOT NULL DEFAULT 0 AFTER edituserid
Error code: ddlexecuteerror

×Stack trace:
line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
line 1072 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 77 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
line 545 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
line 712 of /mod/studentquiz/db/upgrade.php: call to database_manager->add_field()
line 818 of /lib/upgradelib.php: call to xmldb_studentquiz_upgrade()
line 524 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1869 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()
~~~

**Comment by dionysius** [comment]
Please report me the contents commented here: https://github.com/frankkoch/moodle-mod_studentquiz/issues/233#issuecomment-633209296

**Comment by dionysius** [comment]
I was able to reproduce it. I had an old installation where I upgraded studentquiz step by step. Seems like something is wrong for v4.2.0 or before. Working on the cause and the fix

**Comment by dionysius** [comment]
So the change responsible to add `edited` and `edituserid` to the database: https://github.com/frankkoch/moodle-mod_studentquiz/commit/3d45959d6300d096ee764d437ce0991ca9c2e41f#diff-c74097fbb0a2db56a0a98aaf7d6a2654R594 refers to studentquiz internal database version `2020021300` and got introduced in StudentQuiz `v4.2.0`. The internal database version should have been between the version `v4.1.2` [(which is `2020021800`)](https://github.com/frankkoch/moodle-mod_studentquiz/blob/v4.1.2/version.php#L31) and `v4.2.0` [(which is `2020050100`)](https://github.com/frankkoch/moodle-mod_studentquiz/blob/v4.2.0/version.php#L31). Since `2020021800` is **not** less than `2020021300`, that part of upgrade code was never executed. Fix available soon

**Comment by dionysius** [comment]
Fix is released, use v4.3.1 instead

**Comment by dionysius** [comment]
By the way, that means noone (including us) has noticed that editing comments were not working in v4.2.0 if you had a StudentQuiz initially installed in v4.1.2 or earlier

**Comment by AdrianoRuseler** [comment]
Just confirming that the issue has been fixed! Thanks!

**Comment by dewray** [comment]
Upgrade from fresh install of the version before v.4.3.1 to v4.3.1 worked.
