### ISSUE TITLE
bugs with comment history

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#234]
cc @frankkoch @HuongNV13 
While testing manually, since upgrading and restoring can't be tested automatically, I've found two bugs in the comment history.

1) You had a comment (writing `a`) in v4.2.0. Now upgrade to currently `master`. You edit it (writing `b`), you will lose the previous comment in the history, as the history is only showing the current last comment. Full history here: `b` - `a` is lost.

What should be there: `b`, `a`.

2) Similiar to 1, but a special case: If you had a comment in v4.2.0 (writing `1`), and edited itself in v4.2.0 (writing `2`). Since you don't have a comment history in v4.2.0, only `2` is kept, but you edited that comment once. Now upgrade to currently `master`. You get now the option to view history, but the history is empty and you get greeted with an error message:

```
Invalid get_string() identifier: 'nocommenthistoryexist' or component 'mod_studentquiz'. Perhaps you are missing $string['nocommenthistoryexist'] = ''; in mod/studentquiz/lang/en/studentquiz.php?
line 353 of /lib/classes/string_manager_standard.php: call to debugging()
line 7318 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 2072 of /mod/studentquiz/renderer.php: call to get_string()
line 77 of /mod/studentquiz/commenthistory.php: call to mod_studentquiz_comment_history_renderer->render_comment_history()

[[nocommenthistoryexist]]
```

What should be there: `2`.

I think 2) is the same issue as 1), just with a different outcome. The difference can be forced, if someone edited that comment before (=2) or after the upgrade (=1)

**Comment by HuongNV13** [comment]
The comment history only cover for newly created comment, and it does not cover for old comment. So Point 1 is the expected behaviour (For current code)

Point 2 have the same issue with Point 1. But I forgot to add the nocommenthistoryexist language string.

I can add it again if you want

**Comment by dionysius** [comment]
I thought about that. Since if you edited in v4.2.0 you anyway don't see the original comment. So for me we are release ready, I'll have a chat with @frankkoch

**Comment by dionysius** [comment]
I've spoken with frank and we can release it this way.
