### ISSUE TITLE
character encoding in tags

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#235]
Hello,
is there a way to fix character encoding in tags, they do not show properly for national characters:

![coding-tag](https://user-images.githubusercontent.com/1047336/82907429-e6730680-9f66-11ea-9fac-dfd0a5820bba.PNG)

**Comment by dionysius** [comment]
If I remember correctly we cut long tags to a specific length. This looks like the cut is between two chars which are supposed to be together. I have to look up if there's a php function understanding that

**Comment by dionysius** [comment]
Probably that: https://www.php.net/manual/de/function.mb-strcut.php

**Comment by timhunt** [comment]
Or, in Moodle core_text::...

**Comment by timhunt** [comment]
Or, don't actually cut the text, use CSS to limit the width, with text-overflow: ellipsis, which is I think what core question bank does.

**Comment by dionysius** [comment]
Thanks for that hint! I'll look into that
