### ISSUE TITLE
Moving questions into StudentQuiz category

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#24]
Hello !

The StudentQuiz activity creates own category of questions. Students questions can be moved to outside categories, but questions from outside categories can not be moved inside the StudentQuiz category.

See https://moodle.org/mod/forum/discuss.php?d=361738 

Because my students started to create questions with the role ["Question Creator"](https://docs.moodle.org/33/en/Question_creator_role), their questions can not be moved into the StudentQuiz category so that they can continue to work there.

Any remedy for that ?

**Comment by frankkoch** [comment]
StudentQuiz allows to import and export questions in the many Moodle standard formats. So, just create e.g. a Moodle XML file with your questions and import this into your StudentQuiz activity.

**Comment by dionysius** [comment]
Hi @miroi 

I'm not totally aware about the categories completely, but I believe you're looking for the questionbank in the context of your studentquiz activity. In that questionbank context you are then allowed to move questions from and to the studentquiz category.

In the old StudentQuiz the navigation was on the left side in the "user navigation":
![screenshot from 2017-11-27 19-53-31](https://user-images.githubusercontent.com/1341084/33284102-342d99ee-d3ae-11e7-9512-e858262c4bd0.png)

Recent StudentQuiz links are in the activity settings navigation:
![screenshot from 2017-11-27 19-56-00](https://user-images.githubusercontent.com/1341084/33284103-34497b64-d3ae-11e7-9f88-f7515e3f5c4c.png)

Try to use the question bank from there. Would like to know if you already were there or if this is the correct hint for this kind of issue.

**Comment by miroi** [comment]
This works, thanks ! I just moved students questions from  StudentQuiz accessible Question bank categories into the StudentQuiz category. 

My students, who prepared  questions outside the StudentQuiz, now can work more effectively on their questions inside the StudentQuiz.
