### ISSUE TITLE
Missing questions

### ISSUE THREAD

**Issue by sehomer** [frankkoch/moodle-mod_studentquiz#243]
Hello,

this is the second time a teacher tells us that questions of a student quiz activity are missing. In the first case I thought that they have might be deleted by them by mistake. Any ideas to solve this or to where to search for the questions? We use Moodle 3.5 and Student Quiz 2020021800. 

The questions have not been moved to the question bank.

Any hints or help are appreciated. 
Best regards
Sebastian

**Comment by dionysius** [comment]
Hi @sehomer. You probably hit bug #173 which has been fixed since v4.2.0 (2020050100), so you need to upgrade studentquiz to prevent this from happening again.

**Comment by dionysius** [comment]
I'm gonna close this issue. If you think my assumption is wrong, feel free to comment and open again!
