### ISSUE TITLE
Behat comment area failing in only Moodle 35

### ISSUE THREAD

**Issue by dionysius** [frankkoch/moodle-mod_studentquiz#246]
Hi @HuongNV13 

The behat is failing in scenarios related to comment area in **only** Moodle 35. For reference: https://travis-ci.org/github/frankkoch/moodle-mod_studentquiz/jobs/696455598

> Then I set the field "True" to "1"
> WebDriver\Exception\MoveTargetOutOfBounds: Offset within element cannot be scrolled into view: (0, 0): [object HTMLInputElement]

> Then I should see "1" in the ".qno" "css_element" 
> Css_element matching locator ".qno" not found.

Since Moodle 35 is still the current LTS we should fix those errors. Both indicate that there's a view issue, maybe we need to virtually scroll. Do you have an idea how to achieve that?

**Comment by HuongNV13** [comment]
Since I only cover to backport for 2 versions (master 3.9, 3.8 and 3.7), I didn't aware of this issue.

I will investigate the root cause and try to find out the solution and get back to soon.

**Comment by dionysius** [comment]
We could also skip those tests for 3.5, but I couldn't find out how we can do a conditional skip based on moodle version

**Comment by HuongNV13** [comment]
Last time I already made that code. You can refer at: https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/tests/behat/behat_mod_studentquiz.php#L76

**Comment by dionysius** [comment]
https://github.com/frankkoch/moodle-mod_studentquiz/commit/a425aceb6540b07534579d11c9ef008f4a88cc55 fixed this a while ago
