### ISSUE TITLE
Scheduled task to delete orphaned /not approved questions

### ISSUE THREAD

**Issue by tkorner** [frankkoch/moodle-mod_studentquiz#255]
To keep the database clean and tidy, it would be necessary to delete orphaned questions from time to time. Therefore we propose a scheduled task to be available at the administration page for deleting all questions which are flagged as "delete" and questions which never has been touched (anything not approved). This task could be run every year or so.
What do you think?
Best regards
Thomas

**Comment by frankkoch** [comment]
Thanks for the idea Thomas! 

Regarding the "deleted" questions, this is a nice-to-have feature for the admin. However, you could accomplish this within the DB as well. 

Regarding the "not yet approved" questions: some student groups might be on their own, and some teachers might not consider to check questions at all. Nevertheless, they don't want their question sets to be deleted. It's also arguable what an appropriate elapse time might be. I don't want to risk an unintended deletion.

I leave this issue open for a while, maybe somebody else wants to comment.

Best, Frank

**Comment by nexterday** [comment]
Hi Frank

We can not afford a human mistake accessing the database directly:-) let alone adding an extra administrative work on sysadmins.

Ideally a scheduled task would give the option for users to decide on when and how frequently to run, and for whomever doesnt want to use the feature, they can disable the task easily.

If you do not have capacity or time for it, I’m happy to add this feature and make a pull request. Let me know, as this feature is critically important for us.

Thanks Thomas also for bringing up the matter.

**Comment by frankkoch** [comment]
Hi Nexterday, I would be happy to get your PR.
Thank you in advance

**Comment by nexterday** [comment]
Hi Frank, yup sure.. will do a PR when its done. Thanks a lot and appreciated.

**Comment by dionysius** [comment]
I'm currently on holiday, so my answer is short, but I want to prevent effort beeing spent wrong. Moodle itself does not delete questions once it was used in a "question usage". We follow that implementation. We should consider that, before planning changes

**Comment by nexterday** [comment]
> I'm currently on holiday, so my answer is short, but I want to prevent effort beeing spent wrong. Moodle itself does not delete questions once it was used in a "question usage". We follow that implementation. We should consider that, before planning changes

Sorry but what question usage table has to do with deleting a stale question? I think you we are on different frequencies here. Not approved or flagged as deleted (or maybe hidden) should not be in question_usage table at all.

in simple: the deleting will go through non approved for certain period and call the core moodle delete_question which is based on specific context (questions in studentquiz context?). 

In complex: the challenge here is even with delete_question, there are many qtypes who have their own tables and their own schema, so the call might (should) need to be directed inside the     question_bank::get_qtype($question->qtype, false)->delete_question(
            $questionid, $question->contextid)  of those questions to make sure the cleaning process is perfect.

by the way: moodle clearly states that: questions should not be left behind when they are not used any more. Check question_remove_stale_questions_from_category for an example.

**Comment by dionysius** [comment]
I'm just saying. I just reflected what we do now and why we do that, because we had no different opinion **yet**.

Btw the task is more difficult than you think: Previewing a question puts a question into a question usage. You can preview a question in any state (teacher, student if it is his own question, and those with capability previewothers). So a question is in a question usage quicker than you might think and thats why I pointed that out.

**Comment by dionysius** [comment]
I'm not trying to say that we can't do differently. Beeing able to get the question out from moodle at all, and how we want to achieve that, is where we should start discussing. Cleaning up the parts in studentquiz is easy

**Comment by nexterday** [comment]
Question usage keeps filling regardless and thats no problem at all for us, and shall we want to decide to delete them (albeit we never wanted too so long as they are harmless there) we just call question_engine::delete_questions_usage_by_activities. Again: question usage is not of our interest although no harm to delete them.

Re doing the “complex” part, we are happy to dive into it shall you prefer a pull request from our side? We are also ultimately happy if you prefer to do it; we like the plugin but we are concerned about “spam” due to possible lack of action from teachers - and thats a deal breaker for us.

**Comment by dionysius** [comment]
https://wimski.org/api/3.8/d6/d9f/group__moodlecore.html#gaeeb038e3e56e9740054da7def34bc630 is what we use now. We really try to delete a question, but moodle does not as long as it has been used (=question usage)

**Comment by nexterday** [comment]
> https://wimski.org/api/3.8/d6/d9f/group__moodlecore.html#gaeeb038e3e56e9740054da7def34bc630 is what we use now. We really try to delete a question, but moodle does not as long as it has been used (=question usage)

Wrong function used.

**Comment by dionysius** [comment]
Goid,

**Comment by dionysius** [comment]
misclick

**Comment by dionysius** [comment]
Good, than we can improve that as well. Looking forward for your suggestion

**Comment by nexterday** [comment]
So you prefer to do it on your side? If so: a task shall run by default once a year. This task to fo through non approved (or any stale question that is hanging there not used at all for example hidden or or - you know them better) and call the question_bank::get_qtype($question->qtype, false)->delete_question(
$questionid, $question->contextid) to delete all question data. A simple mtrace telling the count number of maybe the question name would be nice-to have.

What do you think?

**Comment by dionysius** [comment]
Good morning, we appreciate any help. I have not yet defined an opinion on the corner cases in detail.

**Comment by tkorner** [comment]
Was this issue solved or what is the reason for closing it?

**Comment by frankkoch** [comment]
I'm not sure if Nexterday is working on a solution. But once it becomes available, we can reopen the issue.

**Comment by Clyxz** [comment]
Hello there,
I am currently working on a solution for this. As soon as it is finished I will send a Pull Request,
best,
Martin

**Comment by nexterday** [comment]
> I'm not sure if Nexterday is working on a solution. But once it becomes available, we can reopen the issue.

Hi Frank - my colleague Martin is assigned to this task and once we have it done, we will let you know. Thanks a lot and apologies for the delay; our schedule is full.
