### ISSUE TITLE
Upgrade broken

### ISSUE THREAD

**Issue by nwp90** [frankkoch/moodle-mod_studentquiz#27]
Testing upgrade of studentquiz from 2.0.3 fails, with:

> Debug info: ERROR: null value in column "roleid" violates not-null constraint
> DETAIL: Failing row contains (3958, 1, null, mod/studentquiz:addinstance, 1, 1516938184, 2).
> INSERT INTO mdl_role_capabilities (contextid,roleid,capability,permission,timemodified,modifierid) VALUES($1,$2,$3,$4,$5,$6) RETURNING id
> [array (
> 'contextid' => 1,
> 'roleid' => NULL,
> 'capability' => 'mod/studentquiz:addinstance',
> 'permission' => 1,
> 'timemodified' => 1516938184,
> 'modifierid' => '2',
> )]
> Error code: dmlwriteexception
> Stack trace:
> 
>     line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
>     line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
>     line 886 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
>     line 934 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->insert_record_raw()
>     line 1308 of /lib/accesslib.php: call to pgsql_native_moodle_database->insert_record()
>     line 4561 of /lib/accesslib.php: call to assign_capability()
>     line 335 of /mod/studentquiz/db/upgrade.php: call to role_change_permission()
>     line 802 of /lib/upgradelib.php: call to xmldb_studentquiz_upgrade()
>     line 508 of /lib/upgradelib.php: call to upgrade_plugins_modules()
>     line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
>     line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by nwp90** [comment]
Seems this is because a role archetype doesn't have to actually exist as a role, and the code assumes that it will.

**Comment by nwp90** [comment]
I'm not clear exactly what the section of code in question:
```
    // Update capabilities list and permission types, to make sure the defaults are set after this upgrade.
    if ($oldversion < 2017112602) {
        // Load current access definition for easier iteration.
        require_once(dirname(__DIR__) . '/db/access.php');
        // Load all contexts this has to be defined.
        // Only system context needed, as by default it's inherited from there.
        // if someone did make an override, it's intentional.
        $context = context_system::instance();
        // Load the roles for easier name to id assignment.
        $roleids = $DB->get_records_menu('role', null, '', 'shortname, id');
        error_log(print_r($roleids, true));
        // And finally update them for every context.
        foreach ($capabilities as $capname => $capability) {
            error_log(print_r($capability, true));
            if (!empty($capability['archetypes'])) {
                foreach ($capability['archetypes'] as $role => $captype) {
                    role_change_permission($roleids[$role], $context, $capname, $captype);
                }
            }
        }
```
is trying to do - it looks like it is trying to change the permission for each of a list of capabilities, in the system context, for each archetype (and hope that all others will inherit appropriately from there)?

If so, that seems wrong to me - the archetypes are hardcoded, and not the same thing as roles which happen to have the same name. It seems to me that this entire chunk of code may be unnecessary as well as broken...

**Comment by dionysius** [comment]
Hi Nick! @nwp90 

This was coming from an old bug: the non-editing teacher was unable access to studentquiz v2.0.3 because the archetype definition was missing. Additionally, v2.0.3 was using the legacy definitions.

If moodle does a upgrade of a module, it will:
- add the capabilities if missing
- update the capabilities if existing
- and remove any removed capabilities
But it seems not to do anything about role permissions. Observations were, correcting the access.php and doing a clean upgrade of the module don't correct past mistakes and the missing captypes were still missing for these roles.

This upgrade step has indeed a bug according false assumptions on role to archetype. Following patch should better reflect the wished effect:

```
diff --git a/db/upgrade.php b/db/upgrade.php
index bb4ba01..464eda1 100644
--- a/db/upgrade.php
+++ b/db/upgrade.php
@@ -326,13 +326,13 @@ function xmldb_studentquiz_upgrade($oldversion) {
         // Only system context needed, as by default it's inherited from there.
         // if someone did make an override, it's intentional.
         $context = context_system::instance();
-        // Load the roles for easier name to id assignment.
-        $roleids = $DB->get_records_menu('role', null, '', 'shortname, id');
         // And finally update them for every context.
         foreach ($capabilities as $capname => $capability) {
             if (!empty($capability['archetypes'])) {
-                foreach ($capability['archetypes'] as $role => $captype) {
-                    role_change_permission($roleids[$role], $context, $capname, $captype);
+                foreach ($capability['archetypes'] as $archetype => $captype) {
+                    foreach(get_archetype_roles($archetype) as $role) {
+                        role_change_permission($role->id, $context, $capname, $captype);
+                    }
                 }
             }
         }
```

We could've also decided not to change anything and let the admin know what he manually has to do to set the default values, with the help of the upgrade notes or manual, but we aimed to help here out.

But I'm unable to safely test it and integrate right now. I hope someone can pick that up.

**Comment by nwp90** [comment]
OK, that makes a lot more sense now. I wasn't sure whether the archetype permissions were taken into account at runtime or whether they were copied into the roles... seems they must be copied.
