### ISSUE TITLE
Unable to "flag" question on in attempt/preview

### ISSUE THREAD

**Issue by atbinix** [frankkoch/moodle-mod_studentquiz#273]
Hi, 

We found an issue with "flagging" questions in mod_studentquiz. The "Flag question" appears to be only text (unlike the functional flag class in mod_quiz). Here is the step to replicate:
1- Enter a Moodle course
2-Click on “Turn editing on”
3-Click “Add an activity or resource”
4-Select “StudentQuiz”
5-Enter any title and description and save
6-Click “Create new question” and create any question
7-Click on Start Quiz/Preview question
8-Unable to click flag question on the question numbering as it is just text  [screenshot]
![test-MOOD-10405](https://user-images.githubusercontent.com/19506513/95413126-2b299800-0972-11eb-978a-b8efa6983c80.png)

Observed: The ‘Flag question’ on the question numbering does nothing
Expected: Able to toggle the flag question like in “Quiz” activity

_It appears that the flag functionality hasn't been invoked for StudentQuiz module from the Question library (class question_flags)._  _Latest version, occurring on both Chrome and Firefox_

**Comment by timhunt** [comment]
Are there any error messages in the browser console?

**Comment by atbinix** [comment]
No there isn't any error as far as I can see. The flag acts as Text (the elements part of browser's debugging console shows that as well) so the flag is not interactive and can't be toggled.

**Comment by dionysius** [comment]
Can reproduce it on Moodle 3.9 and latest StudentQuiz

**Comment by dionysius** [comment]
So, the default of Moodle was `question_display_options::VISIBLE`, which was technically true. It's a bug of moodle that the rendering is poorly when this option is set. For StudentQuiz it anyway makes sense to allow marking of question in all cases so it is set to `question_display_options::EDITABLE` - and with that the issue is gone.

**Comment by timhunt** [comment]
That sounds like the right fix.
