### ISSUE TITLE
Behaviour of comments in boost (and child theme boost campus)

### ISSUE THREAD

**Issue by wiebkemueller-hsh** [frankkoch/moodle-mod_studentquiz#274]
Hi,

we found a display issue in boost (and child theme boost campus) with "commenting" questions in mod_studentquiz. Several horizontal lines are displayed, clicking the collapse/expand button "studentquiz-comment-collapse"/"studentquiz-comment-expand" shows no effect. 

Here are the steps to replicate:
1-Enter a Moodle course
2-Click on “Turn editing on”
3-Click “Add an activity or resource”
4-Select “StudentQuiz”
5-Enter any title and description and save
6-Click “Create new question” and create any question
7-Click on Start Quiz
8-Enter a comment and save
9-Click on button "studentquiz-comment-collapse"/"studentquiz-comment-expand"

**Comment by wiebkemueller-hsh** [comment]
![1_student_quiz_boost_comments](https://user-images.githubusercontent.com/72548805/95441892-fbbb6100-095a-11eb-9eb5-720c249d603c.jpeg)
![2_student_quiz_hide_comments_boost](https://user-images.githubusercontent.com/72548805/95441896-feb65180-095a-11eb-8c43-0e2edcd05391.png)

**Comment by dionysius** [comment]
Right now this feels like we have two issues here: buttons not doing anything (might be javascript/ajax) and the strange lines (might be css). I have a few questions which might help us:
- If you preview/play that question again, are the comments still shown?
- If you answer to one of the comments (so a sub-comment is created), and you close and preview that question again, is this sub-comment shown? If not, can you make it appear by pressing the (un-)collapse buttons?
- If you open the DevTools (F12) in your Browser, in there open the tab "Console" (if not already) and while this is open, navigate freshly to the question, do you see there errors reported while the page has been loading?
- If you select the "Pick an element" icon from the DevTools, and use it on each of the bars: What element with its options is each shown in the element tab?
- ~~This part might be a bit difficult to do: In the DevTools, select the "Pick an element" icon and select one of those bars, maybe best one of the middle ones in such a group. This will automatically change the DevTools to change to the elements tab, where there a tab or box (depending on browser) which is called "Styles". I'd like to know the full list of these styles which are applied to that element.~~ Let's wait for that for now.

Can I also have your installed Moodle & StudentQuiz version?

**Comment by wiebkemueller-hsh** [comment]
Hello Dionysius, thanks for looking into this. I answer your questions in the following lines. Hope this helps. Wiebke

    If you preview/play that question again, are the comments still shown?
--> YES
    If you answer to one of the comments (so a sub-comment is created), and you close and preview that question again, is this sub-comment shown? If not, can you make it appear by pressing the (un-)collapse buttons?
-->YES, the collapse/show functionality of subcomments work fine
    When you have multiple comments, does the sorting buttons actually change the order of the comments?
-->YES, the sorting functionality of subcomments work fine
    If you open the DevTools (F12) in your Browser, in there open the tab "Console" (if not already) and while this is open, navigate freshly to the question, do you see there errors reported while the page has been loading?
    While the DevTools on tab "Console" still open, can you provoke errors by using the different buttons for collapsing, sorting etc.?
    If you select the "Pick an element" icon from the DevTools, and use it on each of the bars: What element with its options is each shown in the element tab?
--> NO
    If you select the "Pick an element" icon from the DevTools, and use it on each of the bars: What element with its options is each shown in the element tab?

--> If I pick the area behind the editor the following is displayed: 
![grafik](https://user-images.githubusercontent.com/72548805/95860533-740d9200-0d60-11eb-859c-717905032949.png)

This part might be a bit difficult to do: In the DevTools, select the "Pick an element" icon and select one of those bars, maybe best one of the middle ones in such a group. This will automatically change the DevTools to change to the elements tab, where there a tab or box (depending on browser) which is called "Styles". I'd like to know the full list of these styles which are applied to that element. Let's wait for that for now.

Element {
}
.studentquiz_behaviour .comment_list div {
    border-bottom: 1px solid #fff;
    border-top: 1px solid #eee;
    padding: 15px 0;
    position: relative;
}
*, ::before, ::after {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}
body {
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    text-align: left;
}
body {
    font-family: sans-serif;
}
:root {
    --color-annotation-summary: #b8ebb8;
    --color-annotation-comment: #ffd7a3;
    --color-annotation-directquotation: #b4d2ff;
    --color-annotation-indirectquotation: #e7b7ff;
    --color-annotation-quickreference: #d52b1e;
    --color-annotation-highlight: #d66800;
}
:root {
    --blue: #007bff;
    --indigo: #6610f2;
    --purple: #6f42c1;
    --pink: #e83e8c;
    --red: #dc3545;
    --orange: #fd7e14;
    --yellow: #ffc107;
    --green: #28a745;
    --teal: #20c997;
    --cyan: #17a2b8;
    --white: #fff;
    --gray: #6c757d;
    --gray-dark: #343a40;
    --primary: #575151;
    --secondary: #6c757d;
    --success: #28a745;
    --info: #17a2b8;
    --warning: #ffc107;
    --danger: #dc3545;
    --light: #f8f9fa;
    --dark: #343a40;
    --breakpoint-xs: 0;
    --breakpoint-sm: 576px;
    --breakpoint-md: 768px;
    --breakpoint-lg: 992px;
    --breakpoint-xl: 1200px;
    --font-family-sans-serif: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
    --font-family-monospace: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
}
html {
    font-family: sans-serif;
    line-height: 1.15;
    -webkit-text-size-adjust: 100%;

Can I also have your installed Moodle & StudentQuiz version? Oh, and what browser are you using?
--> I tested in Mozilla Firefox
StudentQuiz
mod_studentquiz
v4.3.3
2020081100

Boost Campus
theme_boost_campus
v3.8-r1
2020032400
![grafik](https://user-images.githubusercontent.com/72548805/95859856-8935f100-0d5f-11eb-825a-de1e3686ccf1.png)

**Comment by dionysius** [comment]
Thank you very much! This seems to me that generally the functionality is ok. I'm gonna make little improvements to the texts, so the expectations for what these links/buttons do is clearer.

So the focus is now mainly on the styling side. I try reproduce this theme combination.

**Comment by dionysius** [comment]
I couldn't reproduce the visual bug. But I do see that you have a styling section additional than what I observed:
![Screenshot from 2020-10-13 18 15 17](https://user-images.githubusercontent.com/1341084/95887549-46384580-0d80-11eb-98b7-71de0e8170db.png)

There is no such style in StudentQuiz:
![Screenshot from 2020-10-13 18 13 54](https://user-images.githubusercontent.com/1341084/95887555-46d0dc00-0d80-11eb-98d6-df808f532b92.png)

But I found out there is such style in qbehaviour_studentquiz:
https://github.com/frankkoch/moodle-qbehaviour_studentquiz/blob/master/styles.css#L21

The behaviour plugin should not be used anymore, it has no effect anymore - well, it should have not. Everything is now integrated in the main StudentQuiz plugin. Uninstall this behaviour and it should look fine again.

We tried to automatically uninstall the plugin in the upgrade process [here](https://github.com/frankkoch/moodle-mod_studentquiz/blob/609b2097aea3799435f763955154ba78b04ee5da/db/upgrade.php#L293). And in the plugin settings of studentquiz in the site administration you should have also a notice to its uninstallation [as coded here](https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/settings.php#L87).

But if someone installs it again later and never checks the plugin settings :cry:

**Comment by frankkoch** [comment]
I will ask David Mudrák to delete https://moodle.org/plugins/qbehaviour_studentquiz

**Comment by dionysius** [comment]
Feel free to reopen the issue if removing the plugin **qbehavior**_studentquiz doesn't solve the issue

**Comment by wiebkemueller-hsh** [comment]
Thank you, we will look into this!

-----Ursprüngliche Nachricht-----
Von: Dionysius <notifications@github.com> 
Gesendet: Dienstag, 13. Oktober 2020 18:32
An: frankkoch/moodle-mod_studentquiz <moodle-mod_studentquiz@noreply.github.com>
Cc: Müller, Wiebke <wiebke.mueller@hs-hannover.de>; Author <author@noreply.github.com>
Betreff: Re: [frankkoch/moodle-mod_studentquiz] Behaviour of comments in boost (and child theme boost campus) (#274)

I couldn't reproduce the visual bug. But I do see that you have a styling section additional than what I observed:
 <https://user-images.githubusercontent.com/1341084/95887549-46384580-0d80-11eb-98b7-71de0e8170db.png> 

There is no such style in StudentQuiz:
 <https://user-images.githubusercontent.com/1341084/95887555-46d0dc00-0d80-11eb-98d6-df808f532b92.png> 

But I found out there is such style in qbehaviour_studentquiz:
https://github.com/frankkoch/moodle-qbehaviour_studentquiz/blob/master/styles.css#L21

The behaviour plugin should not be used anymore, it has no effect anymore - well, it should have not. Everything is now integrated in the main StudentQuiz plugin. Uninstall this behaviour and it should look fine again.

We tried to automatically uninstall the plugin in the upgrade process here <https://github.com/frankkoch/moodle-mod_studentquiz/blob/609b2097aea3799435f763955154ba78b04ee5da/db/upgrade.php#L293> . And in the plugin settings of studentquiz in the site administration you should have also a notice to its uninstallation as coded here <https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/settings.php#L87> .

But if someone installs it again later and never checks the plugin settings 😢

**Comment by mudrd8mz** [comment]
@frankkoch Let me discourage form simply deleting the plugin from the plugins directory. Better way might be to hide the existing version there (on the "Versions" tab, click "Hide" button). So there will be no ZIP package to be downloaded and installed. And the description of the plugins should be edited to make it clear that this is a legacy and deprecated plugin now and keep a describe its original purpose and what it evolved to.

If we simply delete it, admins will not have a chance to find out any info about it (imagine someone becoming a new site admin of an existing Moodle installation trying to find out where did this installed plugin come from).

Additionally, let me suggest to rename the plugin to "StudentQuiz behaviour" or even ""StudentQuiz 2.x behaviour" to distinguish it from the existing StudentQuiz activity module.

**Comment by frankkoch** [comment]
#mudrd8mz Makes sense, thank you! The version is hidden now. I like your idea to rename the plugin to "StudentQuiz 2.x behaviour" but I cannot find a way to edit the name. Do I have to ask the admin of the plugin directory to do this?

**Comment by wiebkemueller-hsh** [comment]
Just a quick note: it has worked for our Installation at Hochschule Hannover - our Student Quiz Looks Fine again. Thank you!


Am 14.10.2020 um 17:55 schrieb Frank Koch <notifications@github.com>:

﻿

#mudrd8mz Makes sense, thank you! The version is hidden now. I like your idea to rename the plugin to "StudentQuiz 2.x behaviour" but I cannot find a way to edit the name. Do I have to ask the admin of the plugin directory to do this?

**Comment by mudrd8mz** [comment]
@frankkoch can you try Developer zone > Edit this plugin button?
