### ISSUE TITLE
students do not see their own questions after saving

### ISSUE THREAD

**Issue by krueuw** [frankkoch/moodle-mod_studentquiz#275]
We operate an instance of Moodle 3.8 which is hosted centrally by the German state, so we have no access to the database. A great tool so far. Since the update from 3.7 to 3.8 when creating a new StudentQuiz in version 4.3.2 (old variants from 3.7 no longer exist), students do not see their own questions after saving, regardless of the filter setting. Students can only edit it again after the teacher has confirmed the question and then changed it to changed.

The steps to understand:

1 Click as student “Create new question” and create any question,
2 Filling in the question, title test question,
3 Save,
4 List shows no entry for test question, regardless of the filter,
5 teacher sees new question test question and confirms and then changes to changed,
6 only then a student can edit his question.

However, the behavior as described in https://tube.switch.ch/videos/8194aa08 from 8:20 min is desirable. What can I do?
krueuw

**Comment by dionysius** [comment]
While in all cases the student should be able to see his own question always, I'd like to know the following:
- What state is the question before approval from the teacher? Is that column greyed out which means hidden?
- In the settings of StudentQuiz, what is the field "Question publishing" set to? If you change that to the other option as previously set, does it change the behaviour of the visibility for the student?

**Comment by krueuw** [comment]
_What state is the question before approval from the teacher?_ 

It is invisible to the student and not included in the list. Immediately visible to the teacher with all editing options.
 
_Is that row of the question greyed out (which would mean hidden)?_
The text color for this line for the teacher is gray before anything is done.

_In the settings of StudentQuiz, what is the field "Question publishing" set to?_
I don't have a field with that name. The status of the question is "new" prior to approval. The icon is a rounded square.

_If you change that to the other option as previously set, does it change the behaviour of the visibility for the student?_
If I approve the question as a teacher, the view for student changes. The question is now listed, but cannot be edited, the gear is missing. Only after another change by the teacher to changed can the student also edit. For further questions, the behavior remains with the behavior.

**Comment by dionysius** [comment]
Hmm.. In StudentQuiz v4.3.2 you really should have that option. It's right under the description. Allow me to ask you to have a look again, maybe you have missed it.

![image](https://user-images.githubusercontent.com/1341084/95890856-9ca78300-0d84-11eb-8570-b75ad32e7e68.png)

**Comment by dionysius** [comment]
I've found and solved the bug. Students can now see their own question even if it is hidden. Unfortunately there is an overhaul needed in the affected area to keep the queries safe. It's tracked in #277. This issue is solved automatically once I've improved the section there.

**Comment by krueuw** [comment]
Very well. What is the time horizon for the necessary further adjustments? It is a very good tool for exam preparation :-)

**Comment by dionysius** [comment]
I've split the improvements in two parts. The first part containing the immediate fix for this issue has now been cherry-picked to master and is included in the next release.
