### ISSUE TITLE
a trainer cannot comment on a submitted question

### ISSUE THREAD

**Issue by krueuw** [frankkoch/moodle-mod_studentquiz#282]
After the patched version # 275 under Moodle 3.8 shows the desired behavior, it remains strange that a trainer cannot comment on a submitted question. This would be very helpful to guide the gradual development of the question.
Steps to understand:

1 Click as student “Create new question” and create any question,
2 Filling in the question, title test question,
3 Save,
5 teacher sees new question test question and cannot comment on this question,
6 The comment field can be filled, but the button is inactive.

**Comment by krueuw** [comment]
The editor setting Atto is a workaround. In the long run this is not a useful way, because the range of functions is actually atto ;-)

**Comment by dionysius** [comment]
To understand your issue, you have configured another editor similiar to #283 which leads your users not being able to comment on questions. Once you've configured or enabled atto (and StudentQuiz has implicit atto in the comment section), then your teachers are able to comment?

**Comment by krueuw** [comment]
That is correctly understood.

**Comment by dionysius** [comment]
A quick solution is provided with #287 and is included in the next release
