### ISSUE TITLE
Comment support in TinyMCE and Plain Text missing in 4.3.3

### ISSUE THREAD

**Issue by tlock** [frankkoch/moodle-mod_studentquiz#283]
In the previous version we run (v4.0.4), you could comment accordingly as a Student. In the new updated version, you can only comment on ATTO. 

The button is disabled:
![v4.3.3](https://user-images.githubusercontent.com/258626/97520932-55f49280-19ec-11eb-9267-c152943a62d9.png)

The button is available:
![v4.0.4](https://user-images.githubusercontent.com/258626/97520941-5e4ccd80-19ec-11eb-8be4-5bd62030846d.png)

Please advise on plans to support the other editors.

**Comment by dionysius** [comment]
A quick solution is provided with #287 and is included in the next release
