### ISSUE TITLE
Question content images aren't rendered when added to a question.

### ISSUE THREAD

**Issue by tlock** [frankkoch/moodle-mod_studentquiz#29]
Hi,

Question content images aren't rendered when added to a question.

Replicate steps:
1. create a StudentQuiz activity
2. create a true false question (as a student or instructor)
3. insert an image in the question
4. fill in all other mandatory question fields and the save
5. press preview for the question (see the image is displayed)
6. do the quiz (the image is not visible)

Patch to follow.

**Comment by frankkoch** [comment]
Tnak you for the solution Tim
