### ISSUE TITLE
Upgrade from Version 4.3 to 4.4 Error 

### ISSUE THREAD

**Issue by juerghoerner** [frankkoch/moodle-mod_studentquiz#290]
I receive the following message postgres DB moodle Moodle 3.9.1+ (Build: 20200723)

mod_studentquiz  

Can't find data record in database table context.

More information about this error

×Debug info: SELECT * FROM {context} WHERE id = ?
[array (
0 => '2036',
)]
Error code: invalidrecord
×Stack trace:
line 1599 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1575 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 5289 of /lib/accesslib.php: call to moodle_database->get_record()
line 5678 of /lib/accesslib.php: call to context::instance_by_id()
line 7204 of /lib/accesslib.php: call to context->get_parent_context()
line 2696 of /lib/accesslib.php: call to context_module->get_course_context()
line 98 of /mod/studentquiz/classes/access/context_override.php: call to get_roles_used_in_context()
line 212 of /mod/studentquiz/classes/observer.php: call to mod_studentquiz\access\context_override::ensure_relation()
line 198 of /mod/studentquiz/classes/observer.php: call to mod_studentquiz_observer::apply_capability_override_coursemodule()
line 222 of /mod/studentquiz/classes/observer.php: call to mod_studentquiz_observer::apply_capability_override()
line 821 of /mod/studentquiz/db/upgrade.php: call to mod_studentquiz_observer::module_update_backwardsfix_capability_override()
line 866 of /lib/upgradelib.php: call to xmldb_studentquiz_upgrade()
line 565 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
line 711 of /admin/index.php: call to upgrade_noncore()

**Comment by dionysius** [comment]
You seem to have, for whatever reason, a StudentQuiz activity belonging to a course which doesn't exist correctly. Either the course or parts of that course don't exist anymore and that StudentQuiz is orphan and should be removed, or those course internals are inconsistent.

This should yield empty. Checks if a StudentQuiz instance exists where the course, course module, course module context or course context no longer exists:
```sql
select sq.id as sqid, sq.name as sqname, c.id as courseid, cm.id as cmid, ctxm.id as contextidmodule, ctxc.id as contextidcourse
from mdl_studentquiz sq
left join mdl_course c on sq.course = c.id
left join mdl_course_modules cm on sq.coursemodule = cm.id
left join mdl_context ctxm on ctxm.contextlevel = 70 and ctxm.instanceid = cm.id
left join mdl_context ctxc on ctxc.path = trim(trailing concat('/', ctxm.id) from ctxm.path)
where c.id is null
or cm.id is null
or ctxm.id is null
or ctxc.id is null
```

If the result is not empty, you've found the studentquiz where you need to look deeper into. If the result is empty, we need to dive deeper.

**Comment by juerghoerner** [comment]
two courses, which are deleted. See atteched file.

**Comment by juerghoerner** [comment]
Question: How can I delete the two student quizzes of nonexistent courses? In the database?

**Comment by dionysius** [comment]
Yes in the database, as it's there where the inconsistency is. But I want to point out that all of those listed StudentQuizzes are problematic in the upgrade process because contextidcourse is NULL. The result must be empty or the upgrade will still fail. 

**Please make sure, before deleting anything manually in the database, that you really are sure that you want to delete those.** 

I just pointed out StudentQuizzes which are orphan / where the course is inconsistent.

You have more than those 10 StudentQuizzes right?

**Comment by juerghoerner** [comment]
Yes I have more studentquizzes. Do you **have a query** for deleting a student quiz with wrong course id. 

The otherones, I will export or move the question and than I will delete this studentquizzes in the related cours.

**Comment by dionysius** [comment]
Then I suggest we play it safe first here and do it in steps. It is still possible that the other 8 are fine and my query did not represent the state correctly.

1) Make a backup of your whole moodle so you're anytime able to return to your current state
### I can't guarantee that any of those queries do not contain a mistake!

2) Delete StudentQuizzes and it's related course module and course module context where the course doesn't exist anymore:
```sql
delete sq, cm, ctxm
from mdl_studentquiz sq
left join mdl_course c on sq.course = c.id
left join mdl_course_modules cm on sq.coursemodule = cm.id
left join mdl_context ctxm on ctxm.contextlevel = 70 and ctxm.instanceid = cm.id
where c.id is null
```

3) Try to upgrade to StudentQuiz v4.4.0 again. Do you still get an error?

4) Delete StudentQuizzes and it's related course module and course module context where the course context can't be found via course module:
```sql
delete sq, cm, ctxm
from mdl_studentquiz sq
left join mdl_course c on sq.course = c.id
left join mdl_course_modules cm on sq.coursemodule = cm.id
left join mdl_context ctxm on ctxm.contextlevel = 70 and ctxm.instanceid = cm.id
left join mdl_context ctxc on ctxc.path = trim(trailing concat('/', ctxm.id) from ctxm.path)
where ctxc.id is null
```
The next time you open one of the affected courses, you'll probably be greeted once with a warning stating that the course cache had to be refreshed.

**Comment by juerghoerner** [comment]
Many many thanks for your answer. 
I receive this error. Step 2.: 
Fehler in der SQL-Abfrage: ERROR: syntax error at or near "sq"
LINE 1: delete sq, cm, ctxm
(I use adminer in moodle, with postgresDB)

Step 4. If I go to the courses: This student quizzes are there with all the questions. I tried to delete one of this student quizzes in the course and cannot find the deleted student quiz.

**Comment by dionysius** [comment]
I'd like to **leave step 4 out as long as possible** and check if you can do an upgrade after step 2.

Seems like postgres can't delete from multiple tables in one go without correctly using constraints and I'm unsure if moodle is setting them up.

### Make a backup of your whole moodle so you're anytime able to return to your current state

So this is step 2 in smaller delete chunks compatible with postgres (_unfortunately postgres also can't join on delete which made finding a solution take longer_):
```sql
-- first the course module context
delete
from mdl_context
where id in (
	select ctxm.id
	from mdl_studentquiz sq
	left join mdl_course c on sq.course = c.id
	left join mdl_course_modules cm on sq.coursemodule = cm.id
	left join mdl_context ctxm on ctxm.contextlevel = 70 and ctxm.instanceid = cm.id
	where c.id is null
)

-- then the course module itself
delete
from mdl_course_modules
where id in (
	select cm.id
	from mdl_studentquiz sq
	left join mdl_course c on sq.course = c.id
	left join mdl_course_modules cm on sq.coursemodule = cm.id
	left join mdl_context ctxm on ctxm.contextlevel = 70 and ctxm.instanceid = cm.id
	where c.id is null
)

-- then the studenquiz
delete
from mdl_studentquiz
where id in (
	select sq.id
	from mdl_studentquiz sq
	left join mdl_course c on sq.course = c.id
	left join mdl_course_modules cm on sq.coursemodule = cm.id
	left join mdl_context ctxm on ctxm.contextlevel = 70 and ctxm.instanceid = cm.id
	where c.id is null
)
```

**Comment by juerghoerner** [comment]
Thanks for your help. Great. This query worked as well as the upgrade of the studentquiz modul.

**Comment by dionysius** [comment]
Glad this has worked! It's still very weird that you had StudentQuizzes not belonging to a course.
