### ISSUE TITLE
Accessibility: Block titles for skip links contain <span> tags

### ISSUE THREAD

**Issue by danowar2k** [frankkoch/moodle-mod_studentquiz#292]
The block titles use html_writer to write $bc->title, therefore the generated skip links contain <span> tags.

![image](https://user-images.githubusercontent.com/10991509/99407638-9c545780-28ef-11eb-8aa6-1bdac570b568.png)

I'll provide a fix...

**Comment by dionysius** [comment]
Can you elaborate how you get to this view? Where does this "Skip" come from?
