### ISSUE TITLE
Migrate Continuous Integration from travis-ci.org to travis-ci.com or maybe GitHub Actions

### ISSUE THREAD

**Issue by eXpl0it3r** [frankkoch/moodle-mod_studentquiz#294]
The continuous integration pipeline is currently running on [travis-ci.org](https://travis-ci.org/github/frankkoch/moodle-mod_studentquiz).
Without real announcement to their users, [travis-ci.org will be discontinued by the latest on 31st of December 2020](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions).
As alternative they say to migrate the CI pipeline to travis-ci.com

Ever since the [acquisition of Travis CI](https://techcrunch.com/2019/01/23/idera-acquires-travis-ci/) last year by the private equity company Idera and the soon followed [firing of many developers](https://news.ycombinator.com/item?id=19218036), including senior people with a lot of knowledge, the future of Travis CI looks rather bleak.

As such, I'd recommend switching to [GitHub Actions](https://github.com/frankkoch/moodle-mod_studentquiz/actions), which a) nicely integrates into GitHub, b) has Microsoft as the new owner of GitHub behind it and c) doesn't really seem to go anywhere at the moment. I guess the biggest risk is, that you'd be depend on GitHub even more.
Of course as a first step, one could still migrate to travis-ci.com if it's just about activating the account on that site, but I haven't really done any research on that topic.

**Comment by eXpl0it3r** [comment]
I just tried the migration from travis-ci.org to travis-ci.com and it seems to kind of work. Only the organization/account owner can start the migration. The process is rather unstable and some site refreshes are required. Additionally, it seems the images contain different dependencies, so it might be that the .travis.yml may need to be adjusted.

**Comment by timhunt** [comment]
Don't bother. Because of abuse, travis-ci.com now has extremely limited free resources (1000 minutes processing time ever. I have burned through mine already. The Moodle world is looking for an alternative. Keep an eye on https://github.com/moodlehq/moodle-plugin-ci/issues/47

**Comment by eXpl0it3r** [comment]
FYI, [Travis CI has (temporarily?) stopped](https://twitter.com/james_hilliard/status/1336081776691843072) providing credits for OSS projects, so moving to travis-ci.com really isn't an advisable option.

**Comment by frankkoch** [comment]
Thank you Lukas for the valuable information.

**Comment by dionysius** [comment]
For those interested, the following are the commands to run the different types of tests covered in the ci for the StudentQuiz plugin. **Not all**, but the most important ones. Moodle is managed by mdk in this variant and the codechecker plus moodlecheck plugins must be installed for it.
```bash
cd /to/your/moodle/mod/studentquiz/
mdk phpunit $yourmoodlename --run -s mod_studentquiz -q
mdk behat $yourmoodlename --run -f mod/studentquiz/tests/behat
php ../../local/codechecker/run.php mod/studentquiz
php ../../local/moodlecheck/cli/moodlecheck.php -f=text -p=mod/studentquiz | grep -v "@link"
grunt amd
```

**Comment by dionysius** [comment]
Switch to Github Actions is happening now in #316 for StudentQuiz v4.5.0
