### ISSUE TITLE
Adaptación al banco de preguntas general

### ISSUE THREAD

**Issue by samuelPsicos** [frankkoch/moodle-mod_studentquiz#300]
Hola.

Saben como podría adaptar este complemento al "banco de preguntas" general.

para poder realizar cada alumno las "preguntas falladas por alumno", "añadir comentarios", "valorar la pregunta", etc., en general todas las funcionalidades, pero dentro de los "cuestionarios de examen", realizados por los profesores.

muchas gracias.

**Comment by frankkoch** [comment]
Discussions should be comprehensible for everybody. 
Therefore, please post messages in English only.
