### ISSUE TITLE
 Adaptation to the "General Question Bank"

### ISSUE THREAD

**Issue by samuelPsicos** [frankkoch/moodle-mod_studentquiz#301]
Hi.

They know how I could adapt this plugin to the general "question bank".

to be able to carry out each student the "questions failed by student", "add comments", "assess the question", etc., in general, all the functionalities, but within the "exam questionnaires", made by the teachers.

Thanks a lot.

**Comment by frankkoch** [comment]
Not sure if I understand your request... If you cannot solve your request by using the StudentQuiz filters, you may want to create a **separate** StudentQuiz instance with these "exam questionnaires" provided by your teacher. YOur teacher might want to use the import-feature to fill-up the new StudentQuiz instance.

**Comment by samuelPsicos** [comment]
What I wanted is for the students to be able in relation to the questions already created from the question bank by the teachers:

1. -  Assess the question.
2. -  Comment on the question.
3. - that the student can take an examination questionnaire of ALL the failed questions from the question bank.

**Comment by frankkoch** [comment]
It looks like you want the StudentQuiz functionality for the question bank in general. This is not possible because there is no commenting or filtering for students in the question bank. The only way is to export questions from the question bank and to import them into StudentQuiz. A good expoert/import format ist "Moodle XML".

**Comment by samuelPsicos** [comment]
BEFORE ANYTHING, THANK YOU FOR YOUR ATTENTION AND THE TIME EMPLOYED IN ANSWERING ME
I GET IT.

AND THERE WOULD BE THE POSSIBILITY OF STUDENTS CREATING A PLUGIN, THAT ADAPTS TO THESE FEATURES ALREADY EXISTING IN "moodle-mod_studentquiz" BUT FOR THE GENERAL QUESTIONS BANK?

IT WOULD BE A GREAT TOOL FOR STUDENTS TO ASSESS IF THE CONTENT OF THE QUESTIONS IS WELL FORMULATED AND FITS WITH THE KNOWLEDGE OF THE STUDENTS, AND WOULD MAKE THE TEACHERS ASK BETTER QUESTIONS.

ESPECIALLY THE FUNCTIONALITY OF ASKING THE FAILED QUESTIONS, SINCE IT IS THE BEST FORM OF LEARNING "TRIAL AND ERROR" HEHEHE

AGAIN, THANK YOU VERY MUCH.

**Comment by samuelPsicos** [comment]
Hello

Sorry to bother you again.

What do you think of my proposal, would you consider designing an adaptation of this plugin for the general question bank?

Greetings and Merry Christmas

**Comment by timhunt** [comment]
I think that your proposal, as stated, is not right for Moodle or StudentQuiz.

However, the general idea you are thinking about, more options in the question bank, is something that is being thought about as a change for Moodle 4.0. So, have a look out for that.

**Comment by samuelPsicos** [comment]
Will these functionalities be integrated in moodle 4.0?

**Comment by samuelPsicos** [comment]
Hello again

I have tried to contact Moodle TRacker to adapt this plugin to the generality of moodle. but I have not succeeded,

there would be some way that you could adapt this plugin to all the moodle questions, even if it is the system of commenting the question by the students.

Thanks a lot

a greeting
