### ISSUE TITLE
assigned local role-teacher- can not change question status 

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#302]
Hello, 

in StudentQuiz, I assigned local role "teacher" to my student.

Although he can edit all questions, he is not allowed to change their status - see the picture below (in Slovak). Likewise among StudentQuiz list of permissions I can not see the one for changing question status. Could it be fixed, please ? 

![obr](https://user-images.githubusercontent.com/1047336/103008157-f8387e80-4534-11eb-9658-6245f90214e3.png)

**Comment by dionysius** [comment]
If I understood your question correctly you might be affected by https://github.com/frankkoch/moodle-mod_studentquiz/issues/278, can you change the state using the question preview?

**Comment by miroi** [comment]
Yes, using the question preview the StudentQuiz local role assigned teacher can change the status of the question.

**Comment by dionysius** [comment]
Perfect, then it's the same issue. I'll have a look at it over the next days, keep you updated in #278
