### ISSUE TITLE
students cannot delete their questions 

### ISSUE THREAD

**Issue by juerghoerner** [frankkoch/moodle-mod_studentquiz#305]
The delete icon is visible. After the click the following message appears, as a teacher I can delete the question withou a problem: 
studentquiz version 4.4.1 (2020120400)

Sie haben aktuell nicht die Rechte, dies zu tun (Fragen im StudentQuiz moderieren). 

Debug-Info:
Error code: nopermissions tack trace:

    line 870 of /lib/accesslib.php: required_capability_exception thrown
    line 361 of /mod/studentquiz/classes/question/bank/studentquiz_bank_view.php: call to require_capability()
    line 180 of /mod/studentquiz/classes/question/bank/studentquiz_bank_view.php: call to mod_studentquiz\question\bank\studentquiz_bank_view->process_actions_needing_ui()
    line 934 of /mod/studentquiz/renderer.php: call to mod_studentquiz\question\bank\studentquiz_bank_view->display()
    line 914 of /mod/studentquiz/renderer.php: call to mod_studentquiz_overview_renderer->render_questionbank()
    line 101 of /mod/studentquiz/view.php: call to mod_studentquiz_overview_renderer->render_overview()

**Comment by dionysius** [comment]
I've found the issue and is fixed in the next release
