### ISSUE TITLE
Getting error when adding new tags to existing questions in StudentQuiz

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#312]
Hello,

my students created questions into the StudentQuiz last year, and I am changing these questions. 

When I add a new tag and save the question, I get error "error when writing to the database" and link to https://docs.moodle.org/39/en/error/moodle/dmlwriteexception .

Any clue what can be wrong ? This happens when adding fairly new tag. Adding old tags, which are already in the tag-database, works.

**Comment by miroi** [comment]
When playing with this issue, I found I can not add new tags to any question not only within the StudentQuiz category, but also when I move this question outside of the StudentQuiz category.

**Comment by dionysius** [comment]
This is an interesting issue. I once saw that a very while ago in one of my local installations, but after testing and playing around with import/exports. Do you by accident also have this issue in a StudentQuiz where you made imports?

Apart from that: Technically question creation, modification and tagging is pure moodle core code. I'm unsure right now, but I think tags are tied to a question category. So if someone moves the question into subcategories, are tags also there...?

@miroi Can you give us please the full error message. I believe a `dmlwriteexception` should give us the SQL query what it tried to do. You may have to set the developer options in the site administration for a short time to see that.

**Comment by miroi** [comment]
Closing this issue - it got solved at our Moodle portal in between. Now students question in StudentQuiz accept new tags, which they save into tags-database.
