### ISSUE TITLE
Quiz does not see the studentquiz question category

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#32]
Hello,

when I prepare an ordinary  Quiz,  it can take questions only from the course categories; the Quiz does not see the studentquiz question category. (There is workaround just to duplicate question in studenquiz and move it elsewhere.)

**Comment by frankkoch** [comment]
Hello Miroi, that's because questions become nested within their StudentQuiz acitivity. 

Within a  StudentQuiz activity you can navigate to "Question bank" and from there you can move questions into whatever category you like.

**Comment by miroi** [comment]
Thanks for your kind response,Frank.

I was puzzled why I don't see the StudentQuiz questions category upon creating Quiz when I am the admin :| 

So, you decided to have the StudentQuiz questions category which is outside the course question category. Good. 

Maybe - for the sake of reaching StudentQuiz questions by Quizes - you could consider placing the StudentQuiz questions category (as non-default setting) somewhere into the course question categories. Comments ?
