### ISSUE TITLE
StudentQuiz: activity completion

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#33]
Hello again,

please do you plan to include activity completion indicator based on earned points in the StudentQuiz ?  Would be good to have this feature so that students get motivated to take Quizes in the StudentQuiz...

**Comment by frankkoch** [comment]
Hellp Miroi, activity completion is already on our todo list. Completion criteria should be based on no of questions submitted OR StudentQuiz points achieved.

BTW: the no of questions of each student can already easily be computed within the ranking view.
