### ISSUE TITLE
 pictures not showing up in questions for students

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#34]
Hello again,

I am testing v3.0.1 studentquiz  with Moodle 3.3.  While teacher see pictures in questions, student does not see them.

Any help, please ? 

![no-picture](https://user-images.githubusercontent.com/1047336/36635496-1eccb208-19b6-11e8-8a87-901e6384cec8.png)

**Comment by frankkoch** [comment]
Hello Miroi, this problem is already fixed and available in the master branch. You can download from there.
We haven't created a new release yet because we're working on more issues to come.

**Comment by timhunt** [comment]
Are you using the latest code from the 'main' branch here on github?

I am afraid I have not yet release all the latest bug fixes here to the Moodle plugins DB. There may be a few more in progress, and I am busy.
