### ISSUE TITLE
Teacher can not edit student's question in StudentQuiz

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#36]
When editing student's question in StudentQuiz, I get error, claiming bug must be fixed by programmer:
~~~
Could not load preference popup_provider_mod_studentquiz_changed_permitted. Make sure the component and name you supplied to message_send() are valid.
~~~

**Comment by frankkoch** [comment]
Hello Miroi, thank you for the report. This problem was already reported and I close this issue.
Good news, in spite of the error message all changes to the question are stored properly.

**Comment by miroi** [comment]
Hi Frank,

even with the 3.0.2 version, this error message is showing up again ...  "Could not load preference popup_provider_mod_studentquiz_changed_permitted. Make sure the component and name you supplied to message_send() are valid."

But all changes to the question are stored properly.
