### ISSUE TITLE
All question attributes must be filled when controlling question

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#37]
Hi,

as teacher I would like to check quickly questions created by students.  Upon preview of cloze question, for example, I have to fill all attributes of that question, what could be lenghty.

If it would be possible for teacher to check the question without typing anything...meaning that it shows correct answer.

**Comment by miroi** [comment]
For example, 

in this cloze question I even have to put it all parts - what numbers, strings, choices etc - to enable checking.

Sometimes I can not find out quickly, what goes in - whether number of string.

![cloze-question](https://user-images.githubusercontent.com/1047336/37084376-9e4e408e-21f2-11e8-8948-c00bcef19d87.png)

**Comment by frankkoch** [comment]
Your first issue, preview, yes, this could be improved and I already have it in the todo list.

Your second issue, cloze type, this is not a StudentQuiz issue but an issue for the cloze question type.
