### ISSUE TITLE
invalidcoursemodule upon filtering questions

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#39]
Hi,
I applied filtering of questions according to last name (Moodle 3.3), and it brought me to the error page:
https://docs.moodle.org/33/en/error/moodle/invalidcoursemodule

Any help, please ?

**Comment by miroi** [comment]
I also tried other filtering options, and got the same error. 

Even fast filtering buttons are not working.

**Comment by frankkoch** [comment]
1) The last-name search is a bug that we already have on the todo-list.
2) Fast Filtering works. After clicking one or more of the grey fast-filter buttons, you then have to click the blue Filter-button to execute your query.

**Comment by miroi** [comment]
Ah right, fast filtering works, as I checked. Only lastname search is a bug. Good luck in fixing it.
