### ISSUE TITLE
Backup is failing with an error

### ISSUE THREAD

**Issue by marcusgreen** [frankkoch/moodle-mod_studentquiz#4]
It looks like there is a mis-named class in 
backup_studentquiz_activity_task.class.php
On line 38  the class is called

mod_studentquiz_backup_activity_task
When I think it should be called
backup_studentquiz_activity_task

**Comment by frankkoch** [comment]
Thank you for reporting. This issue is fixed with version 2.0

**Comment by mudrd8mz** [comment]
This is serious as it blocks the course backup from happening.

**Comment by frankkoch** [comment]
I agree, We'll solve this issue.

**Comment by eXpl0it3r** [comment]
Issue is fixed in [v2.0.1](https://github.com/frankkoch/moodle-mod_studentquiz/tree/v2.0.1). It was an issue with syncing up all the branches. The problem didn't exist on the develop branch.
