### ISSUE TITLE
Large file used in Behat test

### ISSUE THREAD

**Issue by timhunt** [frankkoch/moodle-mod_studentquiz#40]
This is quite a minor point, but the file mod/studentquiz/tests/fixtures/studentquiz-export-v2.0.3.xml used in the unit tests is about 3MB. This seems a bit excessive.

It caused me problems because a new PHP install defaults to upload_max_filesize = "2M" (http://php.net/manual/en/ini.list.php). So, this test was failing for me, until I worked out what was going on.

Surely it is possible (and faster!) to test the functionality with a much smaller file. And it would be a better experience for people considering using this plugin if they did not have to debug a Behat failure ;-)

**Comment by frankkoch** [comment]
Thank you Tim, we'll provide a less than 2MB testfile with the next release.

**Comment by dionysius** [comment]
Almost fixed by https://github.com/frankkoch/moodle-mod_studentquiz/commit/99c1fe83e86b446b7d8baea063e92d55fe393461
(I just saw I have to update the behat tests for the count of questions imported)

**Comment by timhunt** [comment]
Great! Thanks :-)
