### ISSUE TITLE
Unapproved questions show to other students

### ISSUE THREAD

**Issue by mkpelletier** [frankkoch/moodle-mod_studentquiz#43]
I am not sure if this is an issue or feature request :-).  I would have expected unapproved questions not to show to other students, or at least have an option where I can select the behaviour.  Is this how it is meant to work?

**Comment by frankkoch** [comment]
This is intended behaviour. Students should not have to wait for the teacher to approve questions, such that a slow teacher cannot block the quiz. Also, many students want to run their own question right after entry. This would become impossibe.

It is well visible whether a question is approved or not, and we wanted to leave it up to the students to run not yet approved questions "at her own risk". There is also a filter for approved only questions.

Last, beside the approval feature, a teacher could also delete a question or move it into another category. This way unwanted questions disappear from the quiz.
