### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by mkpelletier** [frankkoch/moodle-mod_studentquiz#45]
Environment:
Moodle Version: 3.3.5+ (Build: 20180508)
Student_quiz Version: 2018051300
mysql dedicated server (8-core/32gb)
Dedicated web server (8-core/32gb):
apache 2.4.10, php5.6.33
______________________________

I have a student_quiz activity with only 337 questions, but the activity takes up to 3 minutes to load! I assume this is due to a poorly designed query but I have not yet pinned it down.  Prior to the questions being added and student attempts, the activity loaded normally, but now most students do not wait for the page to finish loading due to the long execution time.  

Is anybody else having this issue?

**Comment by mkpelletier** [comment]
I think I found the offending query in the function mod_studentquiz_helper_attempt_stat_select.  This query, or one of the associated joins, is taking forever to execute.  Any ideas on a fix?

**Comment by mkpelletier** [comment]
Temporary workaround until the queries are rewritten:
comment out lines 93-95 in view.php (fake blocks with the stats on the bottom of the questions page).

**Comment by dionysius** [comment]
Hi, i just want to inform you that today will come a release to support Moodle 3.5 (if it gets released), but it won't include any changes for your issue. I also don't know when I'm/we're able to try to reproduce it.

You'r comment out lines remove the blocks on the right completely, can you try to let one or the other active or are both causing this issue?

And maybe can you give an input, what *you think* affects the loading time more: the number of questions or the number of answered questions?

**Comment by frankkoch** [comment]
We did not receive more details on this observation and we cannot confirm any performance issues.
