### ISSUE TITLE
Anonymous setting not honoured by notification emails

### ISSUE THREAD

**Issue by mkpelletier** [frankkoch/moodle-mod_studentquiz#46]
It appears that the notification emails sent by student quiz include the name of commenters or question reviewers even though the activity is set as anonymous.

**Comment by frankkoch** [comment]
Thank you for the report. We're aware of this but didn't see it as a bug so far. But you're right, if StudentQuiz is configured to be anonymous, there shouldn't be any loopholes about this. And if somebody wants to leave her contact data, he could do so with the comment message. So ok, it is added to our todo-list for one of the next releases.

**Comment by frankkoch** [comment]
See #145
