### ISSUE TITLE
"invalid course module ID " when filtering questions

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#51]
Hello,

with the newest 3.0.3 StudentQuiz when I want to filter questions via family name and first name I get this error
~~~
Invalid course module ID

More information about this error
~~~

Any help, please ?

**Comment by dionysius** [comment]
Sounds like a duplicate of https://github.com/frankkoch/moodle-mod_studentquiz/issues/39, issue is known but not actively tracked here on github
