### ISSUE TITLE
form element in question text 

### ISSUE THREAD

**Issue by chithramal** [frankkoch/moodle-mod_studentquiz#52]
adding a form element to question text will ends up with not responding "next" button.
I just copied some html text in the editor which contains something like "<form autocomplete="off" action="http://192.168.1.104/moodle350/question/question.php" method="post" accept-charset="utf-8" id="mform1"><br>

</form>"  gives me this bug  
![image](https://user-images.githubusercontent.com/5915977/40937884-af247a34-685d-11e8-9ef4-1368ef5db0e4.png)

**Comment by dionysius** [comment]
Hi chithramal

Sorry for the late response. Actually the whole question editing and showing is handled by moodle core (actually by moodles question engine). We have almost no influence in these parts.

I only can guess that the html tags are off, but that doesn't help you much...
