### ISSUE TITLE
Filter "Mein letzter Versuch" does not consider "Teilweise richtig"

### ISSUE THREAD

**Issue by kesslerd** [frankkoch/moodle-mod_studentquiz#57]
I have answerd some question which were partially correct, however, when I want to do them again with the filter my last attempt I'm not able to do so

**Comment by frankkoch** [comment]
Partially correct answers are treated like incorrect answers. I testet under v3.1.1 and the filter "My latest attempt" runs just fine. You can check out by yourself at https://studentquiz.hsr.ch/moodle/mod/studentquiz/view.php?id=569.
