### ISSUE TITLE
Ranking System wrong calculation

### ISSUE THREAD

**Issue by p1albrec** [frankkoch/moodle-mod_studentquiz#59]
German:
Hat jemand Fragen erstellt, die noch nie geraten wurden, so zählen diese beim Berechnen der Rating Punkte mit hinein. Bsp: ich habe 1 Frage mit 1 Stern und 8 noch ungeratene Fragen, dann bekomme ich das Durchschnittsrating 1 mal 3 Punkte mal 8 Fragen = 24 Punkte. Es sollten aber nur 3 Punkte sein, denn die nicht gearteten Fragen sollen nicht mitgezählt werden.

**Comment by timhunt** [comment]
Please don't add calls to $DB->set_debug(false) all over the place.

Why are you doing that?
