### ISSUE TITLE
Critical failures on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [frankkoch/moodle-mod_studentquiz#6]
The plugin was not tested on PostgrSQL. You have SQL like
```
WHERE state in ("gradedright", "gradedpartial", "gradedwrong")
```
which is MySQL specific syntax. Double quoted text in PostgreSQL is interpreted as the column name, so visiting Statistics or Rank leads to DML exception:

![image](https://cloud.githubusercontent.com/assets/85831/22823359/7f419062-ef83-11e6-8707-f87af83e6107.png)

The is why we have `$DB->get_in_or_equal()` and we generally suggest to wrap SQL queries to double quotes. Please search for how these things are done in the core.

**Comment by EaseRider** [comment]
I'm Investing some time to solve this problem at the moment

**Comment by EaseRider** [comment]
Has been fixed and tested on PostgreSQL
