### ISSUE TITLE
Filtering of questions by group ?

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#60]
Hello,

In Moodle we like to sort students into groups (and groupings).  Would it be please possible to add group filtering into studentquiz filzer ?

**Comment by frankkoch** [comment]
Hi Miro, yes, I will put it on our (long) todo list.

**Comment by miroi** [comment]
Hello Philipp,  this issue is closed ... please is it closed as solved (accepted), or as rejected ?

**Comment by frankkoch** [comment]
Hello Miroi, we had to close it because of other priorities. It is still on our todo-list but unlikely to be addressed in 2019.
