### ISSUE TITLE
Feature Request: question selfcheck before publication

### ISSUE THREAD

**Issue by ksteitz** [frankkoch/moodle-mod_studentquiz#63]
Make it possible to ckeck and answer the question you created only by yourself at first. The publication happens in a next step after this selfcheck, only then the question gets visible for all users.

**Comment by frankkoch** [comment]
Thank you for this interesting idea. I'm afraid many users might not understand this additional option or forget about publishing after the selfcheck. StudentQuiz has a different approach by making use of the crowd. It's the community that rates and comments (= checks) on questions.

If you need this feature badly, you could create a temporary SQ activity next to the real one. Then the temporary one could be used as a playground for testing.
