### ISSUE TITLE
Is equal to in filter not working for 

### ISSUE THREAD

**Issue by jebarviabb** [frankkoch/moodle-mod_studentquiz#67]
version 2018072400. 
1. Create a course.
2. Turn editing on.
3. Add a StudentQuiz activity.
4. Go to the StudentQuiz activity and click "Create new question" button.
5. Choose True/False (any other question would do as well) and save.
6. Go back to the StudentQuiz activity page.
7. Click "Show more" link belowe the "Filter" section.
8. Type a number (i.e. 4) onto any of the following fields Rating, Difficulty, Attempts, Comments.
for this replication purpose, just type 4 onto Rating and select "is equal to".
9. Click the filter button below.
You will get the stack trace:
```
Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 778 of /mod/studentquiz/classes/question/bank/studentquiz_bank_view.php: call to pgsql_native_moodle_database->get_recordset_sql()
line 163 of /mod/studentquiz/classes/question/bank/studentquiz_bank_view.php: call to mod_studentquiz\question\bank\studentquiz_bank_view->load_questions()
line 833 of /mod/studentquiz/renderer.php: call to mod_studentquiz\question\bank\studentquiz_bank_view->display()
line 815 of /mod/studentquiz/renderer.php: call to mod_studentquiz_overview_renderer->render_questionbank()
line 97 of /mod/studentquiz/view.php: call to mod_studentquiz_overview_renderer->render_overview()

Debug info: ERROR: operator does not exist: numeric ~~* text
LINE 1: ...ND q.hidden = 0 AND q.category = $1 AND ((vo.rate ILIKE $2 E...
```

**Comment by muqiuq** [comment]
This issue only seams to happen with postgresql.
With the other db is just doesn't match anything.

**Comment by muqiuq** [comment]
Fixed the issue for most cases. Still doesn't work with floatingpoint values like 0.5 and postgresql.
