### ISSUE TITLE
Importing questions into StudentQuiz

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#69]
Hello,

from the course question bank I exported questions and wanted to import them into StudentQuiz. However, after opening StudentQuiz and setting import into StudentQuiz category all questions got imported into course's question bank instead, where they got duplicated.

Any help, please ? I have the newest release of StudentQuiz.

**Comment by frankkoch** [comment]
Hi Miroi, make sure that your exported questions do not contain category and context. So doing an export, just deselect these options. 
![capture](https://user-images.githubusercontent.com/12372991/49299025-0edb8b00-f4bf-11e8-9918-3c1e504b68da.JPG)
Then you can import your question file into StudentQuiz or other questionbanks.
