### ISSUE TITLE
Use aggregated values to increase performance

### ISSUE THREAD

**Issue by muqiuq** [frankkoch/moodle-mod_studentquiz#73]
- For all the statistics the tables question_attempts and question_attempt_steps are used. 
- The corresponding SQL Queries do not perform well. 
- This issue will introduce aggregated values to increase the performance. 
- This function will only apply for new StudentQuiz instances. 
- The goal is not to use the both tables mentioned above for all statistics. 
- A manual migration function will be added. Existing StudentQuiz instances (the ones that existed before this modification) can be migrated.
- The automatic update of existing StudentQuiz instances will be introduced in the future.

**Comment by frankkoch** [comment]
Done with release 3.2.1
