### ISSUE TITLE
Implement \core_privacy\local\request\core_userlist_provider

### ISSUE THREAD

**Issue by ewallah** [frankkoch/moodle-mod_studentquiz#74]
The latest changes in the privacy api introduced the \core_privacy\local\request\core_userlist_provider. So the mod_studentquiz privacy provider should include a get_users_in_context and delete_data_for_users function.

**Comment by KietChan** [comment]
Hi @frankkoch  ,

I've pushed the implementation for this interface, could you please help me to review it.

Many thanks, and happy new year :).
Kiet

**Comment by ewallah** [comment]
It looks like this code is doing the job.

However Travis complains about duplicated lines in privacy_test.php (562-569 745-752) and coding style (Closing brace must be on a line by itself).

**Comment by KietChan** [comment]
Thanks ewallah
I've updated the code, Travis should be happy now.

**Comment by muqiuq** [comment]
Could you please make a pull request?
