### ISSUE TITLE
Cannot interact with Create new question or close No questions alert

### ISSUE THREAD

**Issue by HuongNV13** [frankkoch/moodle-mod_studentquiz#76]
Hi Frank,
After upgrade to StudentQuiz v3.2.1, an error has occurred as below:
![image](https://user-images.githubusercontent.com/11548406/50396926-8095b480-079f-11e9-988b-c91fca167d89.png)

This error break the StudentQuiz page so if we click on Create new question button, it was redirected to the error page instead of showing the Question type popup as normal
![image](https://user-images.githubusercontent.com/11548406/50397363-7cb76180-07a2-11e9-9074-be375d532f03.png)

If the StudentQuiz does not have any questions yet, we cannot close the No questions alert. When we click on the X button, nothing happens.

After investigating I found that the root cause comes from https://github.com/frankkoch/moodle-mod_studentquiz/commit/274c38f14be339d1b8cce1e34c54745d47572454
The reason is sometimes the DOM still loading/not yet appear but the PHP code executes the Javascript to process the difficult and rate bar elements very soon so the issue happens.
This issue depends on the complexity of the source code, I tested with Moodle Core source code (do not have a lot of modifying, plugin, etc...), the issue does not happen, but with OU source code, the issue happens every time.

The easiest way to fix this issue is modifies the Javascript code to wait the elements exist or add the extra param true to **$PAGE->requires->js_init_code($renderer->render_bar_javascript_snippet(), true)**, this will make the Javascript code run after the DOM ready

But I think writing Javascript in PHP is not the good way. So we should move the Javascript code from function render_bar_javascript_snippet to new Javascript file and call it like studentquiz.js

Thanks,
Huong Nguyen

**Comment by muqiuq** [comment]
I committed your suggested modification into the develop4 branch.

**Comment by HuongNV13** [comment]
Hi,
The extra param fixes the issue.
But during investigating this, I also found that the Javascript was wrong when creating Rating bar.
![image](https://user-images.githubusercontent.com/11548406/50474073-13c62880-09f2-11e9-9425-b76605199886.png)
As I know, the function will get the rate and myrate from the element. 
If both of them are undefined, set the text to n.a
If rate is undefined -> rate will be 0
If myrate is undefined -> myrate will be 0
After that call the function createStarBar with myrate and rate
But you can see in the picture, you are setting the difficultylevel and mydifficulty to 0, those are part of creating Difficulty bar, not the Rating bar.

I moved the Javascript code to AMD, fix the bug, correct the wrong code for Rating bar in my commit.

Thanks,
Huong Nguyen

**Comment by muqiuq** [comment]
Fixed everything according to your comment. Will be published with next release.

**Comment by HuongNV13** [comment]
As I already mention that writing Javascript in PHP is not a good way. But it up to you.

Thanks,
