### ISSUE TITLE
Handling of Essay questions in Student Quiz

### ISSUE THREAD

**Issue by sehomer** [frankkoch/moodle-mod_studentquiz#78]
Hi Frank,

thanks for providing this plugin, our users like it. However we are faced with a problem: When students create essay questions, students are not able to run the quiz containing these questions. There is no "next" button. Is it because essay questions are not rated automatically? I did not find any hints to avoid essay questions. Or is this issue just affecting my installation? 

Best regards
Sebastian

**Comment by frankkoch** [comment]
Hi Sebastian,

There is a solution with the latest version 3.2.1.  Essay-questions cannot be graded automatically, and therefore you cannot add new essay-questions to StudentQuiz anymore. However, if you already have  existing essay-questions, the "next"-button will show with release 3.2.1.

Best, Frank

**Comment by sehomer** [comment]
Hi Frank,

thanks for the fast reply. I'll install 3.2.1 as soon as possible. 

Best regards
Sebastian
