### ISSUE TITLE
Shuffle choices in questions and self quizes

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#79]
Hello Frank,

with the fresh StudentQuiz module (v3.2.1
2018121800) we discovered problem in self quizes, where multiple choice questions have option of shuffling answers.

When you prepare the self quiz with at least 2 multiple choice questions with shuffling answers, the  second, third... questions do get their answers shuffled upon pressing the check button. This sometimes causes accepting wrong answers, although correct answers were typed, because the shuffling changes the order of answering possibilities.

Here is such example - 2 question (import as Moodle XML), https://drive.google.com/file/d/1z1Qty4opjJ-AkVaheSm8IQBIDasQ1_2M/view?usp=sharing . When you practise all 2 questions in self Quiz, the shuffling of the second question answers causes accepting wrong answer, although correct answer was typed before pressing the "check" button.

**Comment by miroi** [comment]
This behaviour happens also with all other types of question which have the shuffling option (like matching).

**Comment by muqiuq** [comment]
Does this issue also occurs using the Quiz that is part of moodle core? Reason for this question: StudentQuiz uses the question implementation of moodle core.

**Comment by miroi** [comment]
Hi,
no, with the core Quiz module questions with shuffling option "on" are behaving right. This is because upon entering the Quiz shuffle-allowed answers shuffle only once. 

However, in StudentQuiz's "Quiz" this ill shuffling happens from the 2nd question upon pressing check, so correct answer get identified as incorrect.

**Comment by muqiuq** [comment]
Thanks for the bug report. It has been fixed.

**Comment by miroi** [comment]
Looking at https://github.com/frankkoch/moodle-mod_studentquiz/releases , I guess it will be the 3.2.2 version with this issue fixed. Am I right ?

**Comment by frankkoch** [comment]
Yes, 3.2.2 will be released very soon.
