### ISSUE TITLE
email notification

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#80]
Dear Frank,

with the fresh StudentQuiz module (v3.2.1 2018121800), there is no way yet to switch off email notification when somebody comments or (with teacher role) changes the question  ?

When students start to work in the StudentQuiz where I have a lot of my questions, I am getting flooded with so many notification emails,..

**Comment by frankkoch** [comment]
Hi Miroi, you cannot switch off the email notification within StudentQuiz. But you could set the notification preferenced in your profile. Another idea might be to upload the question set using a dummy user account. So the notifications wouldn't be sent to you anymore.
