### ISSUE TITLE
StudentQuiz language localization

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#88]
Hello,
I would be interested in providing Slovak translation of  StudentQuiz...would you please give me (us) some hints on how to modify the source code for a new language ?  Thanks.

**Comment by frankkoch** [comment]
Dear Miroi,

This is very kind of you. Thanks to our great community, StudentQuiz is available in many languages already. But Slovak still needs to be done and you're welcome to add your translation to https://lang.moodle.org/. Please let me know if you face any difficulties.

Thank you very much again and best regards,
Frank
