### ISSUE TITLE
Navigation menu with Boost theme

### ISSUE THREAD

**Issue by marcusgreen** [frankkoch/moodle-mod_studentquiz#9]
The navigation menu does not seem to show with the Boost theme. This means you cannot get to the menu Question bank menu items. Upding the final items in the lib.php file seems to make it appear as follows. This was borrowed from my qpractice module.

/**
 * Extends the settings navigation with the studentquiz settings
 *
 * This function is called when the context for the page is a studentquiz module. This is not called by AJAX
 * so it is safe to rely on the $PAGE.
 *
 * @param settings_navigation $settingsnav {@link settings_navigation}
 * @param navigation_node $qpracticenode {@link navigation_node}
 */
function studentquiz_extend_settings_navigation(settings_navigation $settingsnav, navigation_node $qpracticenode = null) {
    global $PAGE, $CFG;
    require_once($CFG->libdir . '/questionlib.php');
    question_extend_settings_navigation($qpracticenode, $PAGE->cm->context)->trim_if_empty();
}

**Comment by EaseRider** [comment]
navigation has been implemented into boost, further changes might be possible.

**Comment by marcusgreen** [comment]
Thanks, I have downloaded the updated version.
